#+title: Emacs Basics
* Doom emacs
** Doom Emacs Architecture :emacs:
*** Конфигурация :test:
~/.doom.d/~ содержит основные файлы:
- ~init.el~ - включает модули Doom
- ~config.el~ - пользовательская конфигурация
- ~packages.el~ - дополнительные пакеты

Пример включения модулей:
#+begin_src elisp
:lang
(emacs-lisp +lsp)
(python +lsp)
(c-c++ +lsp)

:tools
lsp
debugger

:editor
evil
snippets

:app
(org +roam)
#+end_src

** Leader Key

Doom использует leader клавишу:
SPC

Примеры:
- SPC f f  - открыть файл
- SPC f s  - сохранить файл
- SPC b b  - список буферов
- SPC p p  - открыть проект
- SPC g g  - git

** Buffers
В Emacs работа идет с буферами.
buffer = объект в памяти, содержащий текст.
Файл открывается → создается buffer.

Основные команды:
- SPC b b - список буферов
- SPC b k - закрыть буфер

** Windows (split)
Разделение окна:

- SPC w v - вертикальный split
- SPC w s - горизонтальный split
- SPC w d - закрыть окно

Навигация:

- SPC w h
- SPC w j
- SPC w k
- SPC w l

** Проекты (Projectile)
Проект - это директория с:
- .git
- Makefile
- package.json
- Cargo.toml
-

Команды:
- SPC p p - открыть проект
- SPC p f - файл проекта
- SPC p s - поиск по проекту

** Поиск
Используется ripgrep.
- SPC s p - поиск в проекте
- SPC s s - поиск в файле
- SPC / - поиск в текущем буфере

** Org Mode
Org - формат для заметок.

Пример структуры:
\* Заголовок
\** Подраздел
\*** Детали

Списки:
- пункт
- пункт

Сворачивание:
TAB

** Org Links
:PROPERTIES:
:ID:       d73e6078-9b56-4041-818f-60d4e997827f
:END:
SPC-m-I - создать id раздела который можно использовать как ссылку из других мест
[[id:d73e6078-9b56-4041-818f-60d4e997827f][Самоссылка]]

Ссылка на файл:
[[file:another-note.org]]

Ссылка на сайт:
[[https://example.com]] -> SPC m l l -> [[https://example.com][description]]

** Терминал
Открыть терминал внутри Emacs:
SPC o t

** Справка
Посмотреть что делает клавиша:
SPC h k

** Навигация
TAB - свернуть/развернуть
gj/gk - перемещение по заголовкам

** Прочие заметки
- M=option C=ctrl
- M-x occure = M-s o - регекс матч
- С-x C-, - обереуть в код
** Функции :emacs:functions:
    gd - перейти к определению функции
    C-o - вернуться
    zc - свернуть функцию
    zo - развернуть функцию
    SPC s i - список функций
** ripgrep wgrep :wgrep:
Поиск строки во всех файлах директории

Если это проект (git папка):
SPC s p
s p = search project (ripgrep)
Ввести строку → откроется список совпадений.

Если не проект, а просто папка:
SPC s d
s d = search directory
Выбрать директорию → ввести строку.
Массовая замена во всех файлах

После поиска:

SPC s p
ввел строку → список результатов → дальше:
C-c C-e
Это включает wgrep режим (редактирование результатов как текста).

Дальше:
:%s/старое/новое/g
:wq

- Система меток
#+begin_src elisp
;; Функция поиска по тегам req org-ql
(defun my/org-ql-search-by-tags (tags)
  (interactive
   (list
    (completing-read-multiple
     "Tags: "
     (org-global-tags-completion-table)
     nil nil)))

  (let* ((root (projectile-project-root))
         (files (directory-files-recursively root "\\.org$")))
    (org-ql-search
     files
     `(and ,@(mapcar (lambda (t) `(tags ,t)) tags)))))

(map! :leader
      :prefix ("n" . "notes")
      :desc "Search by tags (project)"
      ":" #'my/org-ql-search-by-tags)

#+end_src
функция поиска по меткам которая возвращает главы с меткой переданной как аргумент SPC n :
Пока что не придумал более удобного способа чем развернутое имя главы с соответствующими метками для навигации
Возможно нужна какая-то иерархия, дерево меток?
** Полезные хоткеи emacs :emacs:hotkey:
SPC m i - создать список
Shift+TAB - свернуть все выпадающие
* Elisp
** Разбор elisp :elisp:

*** Лексическая область - переменная видна в блоке кода где она определена и во вложенных блоках, поиск идет по структуре

#+begin_src python :results output
# x = "глобальная"
# def func():
#     print(x)
# def caller():
#     x = "локальная caller"
#     func()
# caller()
#+end_src
#+RESULTS:
: глобальная

В python используется LEGB - поиск от места определения функции
 Local Enclosing Global Builtin
От вызова x: Local - undef, Enclosing - undef, Global - defined, доступа к caller нет вообще

*** Динамическая область - переменная видна в том месте, где была вызвана функция, поиск идет по вызовам
#+begin_src elisp :results output
(setq x "глобальная")
(defun func ()
  (princ x))
(defun caller ()
  (let ((x "локальная caller"))
    (func)))
(caller)
#+end_src
#+RESULTS:
: локальная caller

От вызова x: Local - undef, идем по вызовам outer -> inner

#+begin_src elisp :results output
;; -*- lexical-binding: t; -*-
(defun make-func ()
  (let ((x "hello"))
    (lambda () (princ x))))
(funcall (make-func))
#+end_src

#+RESULTS:
: глобальная

#+begin_src elsip
(setq x nil)
#+end_src

#+begin_src elisp :results output
;; -*- lexical-binding: t; -*-
(defun make-func ()
  (let ((x "hello"))
    (lambda () (princ x))))
(funcall (make-func))
#+end_src

#+RESULTS:
: nil

** Задачи :elisp:task:
*** Реализовать поиск по тегам с иeрархией :elisp:task:tags:
Для начала сделать так чтобы первый тег был выше по ииерархии остальныз тегов
#+begin_src
:elisp:task:..:
*Elisp
 **Titles_tags

:rust:task:..:
*Rust
 **Titles_tags
#+end_src
Полноценная иерархия слишком неудобно, но первый тег будет отвечать за раздел знаний
Нужено оставить плоский поиск spc n : и добавить иерархический
* Babel
** Вопрос
#+begin_src rust :result stderr :flags "-C debug-assertions"
let array = [1, 2, 3, 4, 5];
let slice: &[u8] = &array[1..4];
//           ^^^^^ тип: ссылка на срез

println!("slice[0] = {}", slice[0]); // 2
println!("slice[1] = {}", slice[1]); // 3
println!("slice[2] = {}", slice[2]); // 4
// println!("slice[3] = {}", slice[3]); // err
#+end_src
- Как вообще работают потоки ввода-вывода, как кастомизировать RESULT или направить stderr?

#+name: данные
#+begin_src python
return [int(1), int(2), int(3), int(4), int(5)]
#+end_src
#+RESULTS: данные
| 1 | 2 | 3 | 4 | 5 |
#+begin_src rust :var data=данные
fn main() {
    let rust_data: Vec<i32> = data.iter().map(|&x| x * 2).collect();
    println!("{:?}", rust_data);
}
#+end_src
#+RESULTS:
: error: Could not compile `cargo4Br2dD`.
- Как эффективно пользоваться именованными блоками

* Тесты
** Резолв python окружения в зависимости от проекта

#+begin_src bash
uv venv --python 3.12
#+end_src

#+begin_src python :results output
import sys; print(sys.version)
#+end_src

#+RESULTS:
: 3.11.14 (main, Jan 14 2026, 21:09:41) [Clang 21.1.4 ]

#+begin_src bash
rm -rf .venv
uv venv --python 3.12
#+end_src

#+begin_src elisp
(org-mode-restart)
#+end_src

#+RESULTS:
: org-mode restarted

#+begin_src python :results output
import sys; print(sys.version)
#+end_src

#+RESULTS:
: 3.12.12 (main, Jan 14 2026, 23:36:32) [Clang 21.1.4 ]

#+begin_src bash
rm -rf .venv
#+end_src

#+begin_src elisp
(org-mode-restart)
#+end_src

#+RESULTS:
: org-mode restarted

#+begin_src python :results output
import sys; print(sys.version)
#+end_src

#+RESULTS:
: 3.9.6 (default, Jan  9 2026, 11:03:41)
: [Clang 17.0.0 (clang-1700.6.4.2)]

** Elsip global пепеменные применяются глобально

#+begin_src elisp :results output
(setq x "глобальная") ;; Она установлена для всего emacs
(defun func ()
  (princ x))
(defun caller ()
  (let ((x "локальная caller"))
    (func)))
(caller)
#+end_src
#+RESULTS:
: локальная caller


#+begin_src elisp :results output
(defun make-func ()
  (let ((x "hello"))
    (lambda () (princ x))))
(funcall (make-func))
#+end_src
#+RESULTS:
: глобальная

#+begin_src elsip
(setq x nil)
#+end_src

#+begin_src elisp :results output
(defun make-func ()
  (let ((x "hello"))
    (lambda () (princ x))))
(funcall (make-func))
#+end_src
#+RESULTS:
: nil
