#+title: Emacs Basics

* Doom Emacs Architecture :emacs:

** Конфигурация :test:

~/.doom.d/~ содержит основные файлы:

- ~init.el~ — включает модули Doom
- ~config.el~ — пользовательская конфигурация
- ~packages.el~ — дополнительные пакеты

Пример включения модулей:

#+begin_src elisp
:lang
(emacs-lisp +lsp)
(python +lsp)
(c-c++ +lsp)

:tools
lsp
debugger

:editor
evil
snippets

:app
(org +roam)
#+end_src

* Leader Key

Doom использует leader клавишу:

SPC

Примеры:

- SPC f f  — открыть файл
- SPC f s  — сохранить файл
- SPC b b  — список буферов
- SPC p p  — открыть проект
- SPC g g  — git


* Buffers

В Emacs работа идет с буферами.

buffer = объект в памяти, содержащий текст.

Файл открывается → создается buffer.

Основные команды:

- SPC b b — список буферов
- SPC b k — закрыть буфер


* Windows (split)

Разделение окна:

- SPC w v — вертикальный split
- SPC w s — горизонтальный split
- SPC w d — закрыть окно

Навигация:

- SPC w h
- SPC w j
- SPC w k
- SPC w l

* Проекты (Projectile)

Проект — это директория с:

- .git
- Makefile
- package.json

Команды:

- SPC p p — открыть проект
- SPC p f — файл проекта
- SPC p s — поиск по проекту


* Поиск

Используется ripgrep.

- SPC s p — поиск в проекте
- SPC s s — поиск в файле
- SPC / — поиск в текущем буфере


* Org Mode

Org — формат для заметок.

Пример структуры:


\* Заголовок
\** Подраздел
\*** Детали

Списки:

- пункт
- пункт

Сворачивание:

TAB


* Org Links

Ссылка на файл:

[[file:another-note.org]]

Ссылка на сайт:

[[https://example.com]]


* Терминал

Открыть терминал внутри Emacs:

SPC o t


* Выполнение команд

Выполнить любую команду:

SPC :


* Справка

Посмотреть что делает клавиша:

SPC h k


* Навигация
TAB - свернуть/развернуть
gj/gk - перемещение по заголовкам


* Прочие заметки :emacs:

- M=option C=ctrl
- C-c \ = M-x org-match-sparse-tree - поиск по аметкм
- M-x occure = M-s o - регекс матч
- С-x C-, - обереуть в код

* Python :python:

    gd - перейти к определению функции
    C-o - вернуться
    zc - свернуть функцию
    zo - развернуть функцию
    o - вставит с начала строки
    SPC s i - список функций


* ripgrep wgrep
Поиск строки во всех файлах директории

Если это проект (git папка):
SPC s p
s p = search project (ripgrep)
Ввести строку → откроется список совпадений.

Если не проект, а просто папка:
SPC s d
s d = search directory
Выбрать директорию → ввести строку.
Массовая замена во всех файлах

После поиска:

SPC s p
ввел строку → список результатов → дальше:
C-c C-e
Это включает wgrep режим (редактирование результатов как текста).

Дальше:
:%s/старое/новое/g
:wq
Emacs автоматически применит изменения во всех файлах
