#+title: M Libs

Процесс отладки библиотеки
Для начала напишем небольшую DLL (назовём её ExampleDll), которая будет что-то выполнять в точке входа:


#+begin_src C
VOID
WINAPI // ??
AllocateAndWrite(
    VOID
) {
    PVOID Memory = VirtualAlloc(NULL, 0x1000, (MEM_COMMIT | MEM_RESERVE), PAGE_READWRITE);
    if(Memory == NULL)
        return;

    memset(Memory, 0x41, 0x1000);
}

BOOL
APIENTRY // ??
DllMain(
    _In_ HMODULE hModule,
    _In_ DWORD   ul_reason_for_call,
    _In_ LPVOID lpReserved
) {
    switch (ul_reason_for_call) {
            case DLL_PROCESS_ATTACH:
                AllocateAndWrite();
            break;
            case DLL_THREAD_ATTACH:
            case DLL_THREAD_DETACH:
            case DLL_PROCESS_DETACH:
            break;
    }
    return TRUE;
}
#+end_src

#+begin_src cmd
D:\code\Work>clang ExampleDLL.c -o Example_O0.dll -shared -lkernel32 -O0
#+end_src


#+begin_src C
__declspec(dllexport)
PVOID
WINAPI
MyVirtualAllocRw(
    _In_ SIZE_T Size
) {
    return VirtualAlloc(NULL, Size, (MEM_COMMIT | MEM_RESERVE), PAGE_READWRITE);
}

__declspec(dllexport)
PVOID
WINAPI
MyVirtualAllocRo(
    _In_ SIZE_T Size
) {
    return VirtualAlloc(NULL, Size, (MEM_COMMIT | MEM_RESERVE), PAGE_READONLY);
}

__declspec(dllexport)
PVOID
WINAPI
MyVirtualAllocRwx(
    _In_ SIZE_T Size
) {
    return VirtualAlloc(NULL, Size, (MEM_COMMIT | MEM_RESERVE), PAGE_EXECUTE_READWRITE);
}

VOID
WINAPI
AllocateAndWrite(
    VOID
) {
    PVOID Memory = VirtualAlloc(NULL, 0x1000, (MEM_COMMIT | MEM_RESERVE), PAGE_READWRITE);
    if(Memory == NULL)
        return;

    memset(Memory, 0x41, 0x1000);
}

BOOL
APIENTRY
DllMain(
    _In_ HMODULE hModule,
    _In_ DWORD   ul_reason_for_call,
    _In_ LPVOID lpReserved
) {
    switch (ul_reason_for_call) {
            case DLL_PROCESS_ATTACH:
                AllocateAndWrite();
            break;
            case DLL_THREAD_ATTACH:
            case DLL_THREAD_DETACH:
            case DLL_PROCESS_DETACH:
            break;
    }
    return TRUE;
}

#+end_src


*** win64dbg :win64dbg:
Alt+F9 = exec to user code

*** RVA :rva:
Exported Function Address = Image Base + Export RVA

*** rundll32 :rundll32:
64-битный rundll32 находится по пути C:\Windows\System32\rundll32.exe,
32-битный аналог находится по пути C:\Windows\SysWOW64\rundll32.exe.

run x64dbg as admin
open rundll32
Нажимаем на пункт "Изменить аргументы командной строки".
Далее вписываем                  путь до запущенного нами rundll32.
После вписываем путь до DLL, которую мы хотим отлаживать, как на картинке ниже. Или можете скопировать сразу эту команду, предварительно вставив путь до своей DLL: "C:\Windows\System32\rundll32.exe" "path\to\name.dll" #1



* Алгоритм
** Алгоритм - загрузка DLL в отладчик без использования rundll32
Узнать через DIE разрядность анализируемой DLL.
Открыть отладчик нужной разрядности.
Во вкладке Параметры, перейти в пункт Параметры, поставить флажок User DLL Entry в первом столбце.
Загрузить DLL через вкладку Файл в отладчике (или используя Drag&Drop, или через клавишу F3).
Нажать один раз на кнопку "Выполнить до пользовательского кода" (или же использовать комбинацию клавиш Alt + F9).
DLL готова к анализу.
** Алгоритм - загрузка DLL в отладчик с использованием rundll32
Узнать через DIE разрядность анализируемой DLL.
Открыть отладчик нужной разрядности.
Во вкладке Параметры, перейти в пункт Параметры, поставить флажок User DLL Entry в первом столбце.
В зависимости от разрядности DLL, открыть через вкладку Файл в отладчике (или используя Drag&Drop, или через клавишу F3) rundll32.exe по пути C:\Windows\System32\rundll32.exe или C:\Windows\SysWOW64\rundll32.exe.
После загрузки rundll32.exe во вкладке Файл нажать на пункт "Изменить аргументы командной строки".
В появившемся окне вписать команду "C:\Windows\System32\rundll32.exe"path\to\name.dll" #1, где "path\to\name.dll" - путь до анализируемой DLL.
Нажать два раза на кнопку "Выполнить до пользовательского кода" (или же использовать комбинацию клавиш Alt + F9).
DLL готова к анализу.
** Алгоритм - отладка экспортируемых функций в DLL
Узнать через DIE разрядность анализируемой DLL.
В DIE во вкладке "Экспорт" узнать RVA интересующей экспортируемой функции.
Загрузить DLL в отладчик нужной разрядности.
Дойти до входной точки DLL.
Во вкладке "Карта памяти" в столбце "Информация" ищем строку с названием анализируемой DLL.
Крайний левый столбец Адрес содержит базовый адрес анализируемой DLL, копируем его.
Прибавляем к скопированному адресу RVA интересующей экспортируемой функции.
Во вкладке с регистрами ищем регистр RIP (или EIP, если анализируем 32-битную DLL) и нажимаем правой кнопкой мыши, в контекстном меню выбираем пункт Изменение значения, вставляем получившийся адрес в пункт "Выражение", затем нажимаем "ОК".
Экспортируемая функция готова к анализу.
* Задача
Нужно понять что делает DLL в своей точке входа и рассмотреть её экспортируемую функцию.

RVA DoSomethingFunny 00001e70

#+begin_src asm
00007FFCDC171344 | 48:895C24 08             | mov qword ptr ss:[rsp+8],rbx            |
00007FFCDC171349 | 48:897424 10             | mov qword ptr ss:[rsp+10],rsi           |
00007FFCDC17134E | 57                       | push rdi                                |
00007FFCDC17134F | 48:83EC 20               | sub rsp,20                              |
00007FFCDC171353 | 49:8BF8                  | mov rdi,r8                              |
00007FFCDC171356 | 8BDA                     | mov ebx,edx                             |
00007FFCDC171358 | 48:8BF1                  | mov rsi,rcx                             | rcx:"MZђ"
00007FFCDC17135B | 83FA 01                  | cmp edx,1                               |
00007FFCDC17135E | 75 05                    | jne unknowndll.7FFCDC171365             |
00007FFCDC171360 | E8 9B010000              | call unknowndll.7FFCDC171500            |
00007FFCDC171365 | 4C:8BC7                  | mov r8,rdi                              |
00007FFCDC171368 | 8BD3                     | mov edx,ebx                             |
00007FFCDC17136A | 48:8BCE                  | mov rcx,rsi                             | rcx:"MZђ"
00007FFCDC17136D | 48:8B5C24 30             | mov rbx,qword ptr ss:[rsp+30]           | [rsp+30]:LdrGetProcedureAddressEx+3CE
00007FFCDC171372 | 48:8B7424 38             | mov rsi,qword ptr ss:[rsp+38]           |
00007FFCDC171377 | 48:83C4 20               | add rsp,20                              |
00007FFCDC17137B | 5F                       | pop rdi                                 |
00007FFCDC17137C | E9 9BFEFFFF              | jmp unknowndll.7FFCDC17121C             |
#+end_src

dbg -> alt+f9->bp на функции

#+begin_src asm
00007FFCF46D1500 | 48:895C24 18             | mov qword ptr ss:[rsp+18],rbx           |
00007FFCF46D1505 | 55                       | push rbp                                |
00007FFCF46D1506 | 48:8BEC                  | mov rbp,rsp                             |
00007FFCF46D1509 | 48:83EC 30               | sub rsp,30                              |
00007FFCF46D150D | 48:8B05 EC2A0000         | mov rax,qword ptr ds:[7FFCF46D4000]     |
00007FFCF46D1514 | 48:BB 32A2DF2D992B0000   | mov rbx,2B992DDFA232                    |
00007FFCF46D151E | 48:3BC3                  | cmp rax,rbx                             |
00007FFCF46D1521 | 75 77                    | jne unknowndll.7FFCF46D159A             |
00007FFCF46D1523 | 48:8D4D 10               | lea rcx,qword ptr ss:[rbp+10]           | [rbp+10]:L"D:\\code\\Work\\UnknownDll.dll"
00007FFCF46D1527 | 48:C745 10 00000000      | mov qword ptr ss:[rbp+10],0             | [rbp+10]:L"D:\\code\\Work\\UnknownDll.dll"
00007FFCF46D152F | FF15 231B0000            | call qword ptr ds:[<GetSystemTimeAsFile |
00007FFCF46D1535 | 48:8B45 10               | mov rax,qword ptr ss:[rbp+10]           | [rbp+10]:L"D:\\code\\Work\\UnknownDll.dll"
00007FFCF46D1539 | 48:8945 F0               | mov qword ptr ss:[rbp-10],rax           |
00007FFCF46D153D | FF15 1D1B0000            | call qword ptr ds:[<GetCurrentThreadId> |
00007FFCF46D1543 | 8BC0                     | mov eax,eax                             |
00007FFCF46D1545 | 48:3145 F0               | xor qword ptr ss:[rbp-10],rax           |
00007FFCF46D1549 | FF15 191B0000            | call qword ptr ds:[<GetCurrentProcessId |
00007FFCF46D154F | 8BC0                     | mov eax,eax                             |
00007FFCF46D1551 | 48:8D4D 18               | lea rcx,qword ptr ss:[rbp+18]           |
00007FFCF46D1555 | 48:3145 F0               | xor qword ptr ss:[rbp-10],rax           |
00007FFCF46D1559 | FF15 111B0000            | call qword ptr ds:[<QueryPerformanceCou |
00007FFCF46D155F | 8B45 18                  | mov eax,dword ptr ss:[rbp+18]           |
00007FFCF46D1562 | 48:8D4D F0               | lea rcx,qword ptr ss:[rbp-10]           |
00007FFCF46D1566 | 48:C1E0 20               | shl rax,20                              |
00007FFCF46D156A | 48:3345 18               | xor rax,qword ptr ss:[rbp+18]           |
00007FFCF46D156E | 48:3345 F0               | xor rax,qword ptr ss:[rbp-10]           |
00007FFCF46D1572 | 48:33C1                  | xor rax,rcx                             | rcx:"MZђ"
00007FFCF46D1575 | 48:B9 FFFFFFFFFFFF0000   | mov rcx,FFFFFFFFFFFF                    | rcx:"MZђ"
00007FFCF46D157F | 48:23C1                  | and rax,rcx                             | rcx:"MZђ"
00007FFCF46D1582 | 48:B9 33A2DF2D992B0000   | mov rcx,2B992DDFA233                    | rcx:"MZђ"
00007FFCF46D158C | 48:3BC3                  | cmp rax,rbx                             |
00007FFCF46D158F | 48:0F44C1                | cmove rax,rcx                           | rcx:"MZђ"
00007FFCF46D1593 | 48:8905 662A0000         | mov qword ptr ds:[7FFCF46D4000],rax     |
00007FFCF46D159A | 48:8B5C24 50             | mov rbx,qword ptr ss:[rsp+50]           |
00007FFCF46D159F | 48:F7D0                  | not rax                                 |
00007FFCF46D15A2 | 48:8905 972A0000         | mov qword ptr ds:[7FFCF46D4040],rax     |
00007FFCF46D15A9 | 48:83C4 30               | add rsp,30                              |
00007FFCF46D15AD | 5D                       | pop rbp                                 |
00007FFCF46D15AE | C3                       | ret                                     |

#+end_src

#+begin_src asm
00007FFCF4B31E70 | 40:53                    | push rbx                                |
00007FFCF4B31E72 | 48:83EC 70               | sub rsp,70                              |
00007FFCF4B31E76 | 48:8B05 83210000         | mov rax,qword ptr ds:[7FFCF4B34000]     | rax:EntryPoint
00007FFCF4B31E7D | 48:33C4                  | xor rax,rsp                             | rax:EntryPoint
00007FFCF4B31E80 | 48:894424 68             | mov qword ptr ss:[rsp+68],rax           | rax:EntryPoint
00007FFCF4B31E85 | 33DB                     | xor ebx,ebx                             |
00007FFCF4B31E87 | 45:33C9                  | xor r9d,r9d                             |
00007FFCF4B31E8A | 48:833D EE270000 01      | cmp qword ptr ds:[7FFCF4B34680],1       |
00007FFCF4B31E92 | BA 00000010              | mov edx,10000000                        |
00007FFCF4B31E97 | 48:895C24 30             | mov qword ptr ss:[rsp+30],rbx           | [rsp+30]:LdrGetProcedureAddressEx+3CE
00007FFCF4B31E9C | 41:B8 07000000           | mov r8d,7                               |
00007FFCF4B31EA2 | C74424 28 80000000       | mov dword ptr ss:[rsp+28],80            |
00007FFCF4B31EAA | C74424 20 02000000       | mov dword ptr ss:[rsp+20],2             |
00007FFCF4B31EB2 | 75 7B                    | jne unknowndll.7FFCF4B31F2F             |
00007FFCF4B31EB4 | 48:8D0D F5120000         | lea rcx,qword ptr ds:[7FFCF4B331B0]     | rcx:"MZђ", 00007FFCF4B331B0:L"C:\\FunFile.txt"
00007FFCF4B31EBB | FF15 47110000            | call qword ptr ds:[<CreateFileW>]       |
00007FFCF4B31EC1 | 48:8BC8                  | mov rcx,rax                             | rcx:"MZђ", rax:EntryPoint
00007FFCF4B31EC4 | 48:83F8 FF               | cmp rax,FFFFFFFFFFFFFFFF                | rax:EntryPoint
00007FFCF4B31EC8 | 74 4C                    | je unknowndll.7FFCF4B31F16              |
00007FFCF4B31ECA | 0F1005 FF120000          | movups xmm0,xmmword ptr ds:[7FFCF4B331D | 00007FFCF4B331D0:"Hello from analyzed DLL!"
00007FFCF4B31ED1 | 0FB605 10130000          | movzx eax,byte ptr ds:[7FFCF4B331E8]    |
00007FFCF4B31ED8 | 4C:8D4C24 40             | lea r9,qword ptr ss:[rsp+40]            |
00007FFCF4B31EDD | 41:B8 19000000           | mov r8d,19                              |
00007FFCF4B31EE3 | 884424 60                | mov byte ptr ss:[rsp+60],al             |
00007FFCF4B31EE7 | 0F114424 48              | movups xmmword ptr ss:[rsp+48],xmm0     |
00007FFCF4B31EEC | 48:8D5424 48             | lea rdx,qword ptr ss:[rsp+48]           |
00007FFCF4B31EF1 | 895C24 40                | mov dword ptr ss:[rsp+40],ebx           |
00007FFCF4B31EF5 | F2:0F1005 E3120000       | movsd xmm0,qword ptr ds:[7FFCF4B331E0]  | 00007FFCF4B331E0:"zed DLL!"
00007FFCF4B31EFD | F2:0F114424 58           | movsd qword ptr ss:[rsp+58],xmm0        |
00007FFCF4B31F03 | 48:895C24 20             | mov qword ptr ss:[rsp+20],rbx           |
00007FFCF4B31F08 | FF15 F2100000            | call qword ptr ds:[<WriteFile>]         |
00007FFCF4B31F0E | 85C0                     | test eax,eax                            |
00007FFCF4B31F10 | 0F85 85000000            | jne unknowndll.7FFCF4B31F9B             |
00007FFCF4B31F16 | FF15 F4100000            | call qword ptr ds:[<GetLastError>]      |
00007FFCF4B31F1C | 48:8B4C24 68             | mov rcx,qword ptr ss:[rsp+68]           |
00007FFCF4B31F21 | 48:33CC                  | xor rcx,rsp                             |
00007FFCF4B31F24 | E8 E7F0FFFF              | call unknowndll.7FFCF4B31010            |
00007FFCF4B31F29 | 48:83C4 70               | add rsp,70                              |
00007FFCF4B31F2D | 5B                       | pop rbx                                 |
00007FFCF4B31F2E | C3                       | ret                                     |
00007FFCF4B31F2F | 48:8D0D BA120000         | lea rcx,qword ptr ds:[7FFCF4B331F0]     | rcx:"MZђ", 00007FFCF4B331F0:L"C:\\RandomFile.txt"
00007FFCF4B31F36 | FF15 CC100000            | call qword ptr ds:[<CreateFileW>]       |
00007FFCF4B31F3C | 48:83F8 FF               | cmp rax,FFFFFFFFFFFFFFFF                | rax:EntryPoint
00007FFCF4B31F40 | 74 D4                    | je unknowndll.7FFCF4B31F16              |
00007FFCF4B31F42 | 0F1005 CF120000          | movups xmm0,xmmword ptr ds:[7FFCF4B3321 | 00007FFCF4B33218:"There's nothing to see!"
00007FFCF4B31F49 | 4C:8D4C24 40             | lea r9,qword ptr ss:[rsp+40]            |
00007FFCF4B31F4E | 895C24 40                | mov dword ptr ss:[rsp+40],ebx           |
00007FFCF4B31F52 | 41:B8 18000000           | mov r8d,18                              |
00007FFCF4B31F58 | 48:895C24 20             | mov qword ptr ss:[rsp+20],rbx           |
00007FFCF4B31F5D | 0F114424 48              | movups xmmword ptr ss:[rsp+48],xmm0     |
00007FFCF4B31F62 | 48:8D5424 48             | lea rdx,qword ptr ss:[rsp+48]           |
00007FFCF4B31F67 | 48:8BC8                  | mov rcx,rax                             | rcx:"MZђ", rax:EntryPoint
00007FFCF4B31F6A | F2:0F1005 B6120000       | movsd xmm0,qword ptr ds:[7FFCF4B33228]  | 00007FFCF4B33228:"to see!"
00007FFCF4B31F72 | F2:0F114424 58           | movsd qword ptr ss:[rsp+58],xmm0        |
00007FFCF4B31F78 | FF15 82100000            | call qword ptr ds:[<WriteFile>]         |
00007FFCF4B31F7E | 85C0                     | test eax,eax                            |
00007FFCF4B31F80 | 75 19                    | jne unknowndll.7FFCF4B31F9B             |
00007FFCF4B31F82 | FF15 88100000            | call qword ptr ds:[<GetLastError>]      |
00007FFCF4B31F88 | 48:8B4C24 68             | mov rcx,qword ptr ss:[rsp+68]           |
00007FFCF4B31F8D | 48:33CC                  | xor rcx,rsp                             |
00007FFCF4B31F90 | E8 7BF0FFFF              | call unknowndll.7FFCF4B31010            |
00007FFCF4B31F95 | 48:83C4 70               | add rsp,70                              |
00007FFCF4B31F99 | 5B                       | pop rbx                                 |
00007FFCF4B31F9A | C3                       | ret                                     |
#+end_src
