#+title: Practice Reverse

* Strings cheat sheet :strings:cs:
-t флаг вывода позиции строки в файле (смещение в файле от 0; x, d, o  hex, decimal, oct)

* Example.exe
:PROPERTIES:
:ID:       139dc0bd-4b0e-462e-a922-d7017ea4e822
:END:

- Задача, понять куда подключается ПО и какой алгоритм шифрования использует

1. Имя может не соответствовать реальному расширению
#+begin_src shell :dir example :results output
file example.exe
#+end_src

#+RESULTS:
: example.exe: PE32+ executable (console) x86-64, for MS Windows

2. Простейшая разведка

#+begin_src shell :dir example :results output
strings -t x -n 6 example.exe
#+end_src

[[https://www.hexacorn.com/blog/2013/05/16/uvwatauavawh-meet-the-pushy-string/][фанфакт про UTAWUHUA]]

Тут явно можно понять что присутствует клиент-серверное взаимодействие

#+begin_src
15790 192.168.0.1
157a0 [int send_data(socket af, char* data) not implemented]
157d8 WSAStartup failed
157f0 Socket creation failed: %d
15810 Connect failed: %d
15830 BCryptOpenAlgorithmProvider failed
#+end_src

3. Ida
   [[id:c9e47c78-f735-43aa-a5e9-78b1ffc5e977][Смежная логика с KPE]]

  ⌥-t - search text -> "Socket creation failed: %d" и мы нашли потенциально интересное место
  Строка используется как первый параметр функции, что может делать подобная запись как параметр?
  Наверное выводиться? -> назовем printf?

 Ниже видем блок в котором есть намеки на шифрование
 строка "AES" и "BCryptOpenAlgorithmProvider failed"

 На самом деле ида сама поняла в чем тут прикол(
 Но в конечном итоге удалось переименовать пользовательские функции по их назначению

* re842_task.exe

- 1.
#+begin_src shell :dir ./re842_task :results output
file re842_task.exe
#+end_src

#+RESULTS:
: re842_task.exe: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=e7eefbf8a6223496ae3df6b621d5d43023b81d3f, for GNU/Linux 3.2.0, stripped

))

- 2.
#+begin_src shell :dir ./re842_task :results output
strings -n 6 re842_task.exe
#+end_src

Первые кандидаты:

AES-NI GCM module for x86_64, CRYPTOGAMS by <appro@openssl.org>
и есть много путей к crypto исходникам
Это намекает что задача связана с шифрованием
Также мы находим ip 10.38.190.16

- 3.
   Ip используется в контексте интересной функции
   #+begin_src C
   __int64 __fastcall sub_402F45(int *a1)
   {
     __int64 result; // rax
     int v2; // [rsp+1Ch] [rbp-24h]
     _QWORD v3[3]; // [rsp+20h] [rbp-20h] BYREF
     unsigned __int64 v4; // [rsp+38h] [rbp-8h]

     v4 = __readfsqword(0x28u);
     v3[0] = 2;
     v3[1] = 0;
     *(_DWORD *)((char *)v3 + 2) = (unsigned __int16)sub_5ED1A0(10988);
     sub_5F28A0(2, "10.38.190.16", (char *)v3 + 4);
     v2 = sub_5ECCE0(2, 1, 0);
     if ( v2 >= 0 )
     {
       if ( (unsigned int)sub_57D060((unsigned int)v2, v3, 16) )
       {
         sub_58D680("connect");
         sub_57CF30((unsigned int)v2);
         result = 0xFFFFFFFFLL;
       }
       else
       {
         *a1 = v2;
         result = 0;
       }
     }
     else
     {
       sub_58D680("socket");
       result = 0xFFFFFFFFLL;
     }
     if ( __readfsqword(0x28u) != v4 )
       sub_5ED100();
     return result;
   }
   #+end_src

*** 3.1 Какой файл логов открывается?
:PROPERTIES:
:ID:       86a9af80-de2d-41fa-82b6-d9841854741e
:END:
   В строках находим путь /var/log/example/err.log -> по xref приходим в
   #+begin_src C
   __int64 sub_402F09()
   {
     __int64 v1; // [rsp+8h] [rbp-8h]

     v1 = sub_5969A0("/var/log/example/err.log", &unk_651030);
     if ( !v1 )
       sub_58D680((__int64)"fopen");
     return v1;
   }
   #+end_src

   - Кандидат на первый ответ
     Чуть чуть разберем его, тут видно что переменная принимает значение функции в которой есть аргументы, первый это путь второй это еще что-то
     И потом проверка - коли ноль то что-то fopen
     Явно это проверка на то что мы взяли по пути то что нужно, а кейс с ошибкой намекает что это ошибка fopen
     Что-то такое
     #+begin_src C
     FILE *file = fopen(path, mode)
          if (!file) {
            perror("fopen")
         }
     #+end_src


Попробуем привести сигнатуры и типы чтобы было красиво
После переименования двух функций к fopen и perror IDA не подтянула типы, в shift+f11 есть GNU C++ x64 но она не предложила прототип через Y
Добавим руками
google -> fopen prototype c -> FILE* fopen(const char* filename, const char* mode);
Добавляем руками через Y и все красиво

#+begin_src C
FILE *fopen_err_log()
{
  FILE *f; // [rsp+8h] [rbp-8h]

  f = fopen("/var/log/example/err.log", "r");
  if ( !f )
    perror("fopen");
  return f;
}

#+end_src
*** 3.2 Сколько строк логов считывается для отправки на сервер?
Если нашли открытие логов, то рядом ищем чтение
По xref идем туда где вызывается функция из [[id:86a9af80-de2d-41fa-82b6-d9841854741e][3.1]]

#+begin_src C
__int64 sub_4032CC()
{
  __int64 result; // rax
  unsigned int v1; // [rsp+4h] [rbp-2Ch] BYREF
  unsigned int v2; // [rsp+8h] [rbp-28h] BYREF
  int v3; // [rsp+Ch] [rbp-24h]
  __int64 v4; // [rsp+10h] [rbp-20h] BYREF
  __int64 v5; // [rsp+18h] [rbp-18h] BYREF
  FILE *v6; // [rsp+20h] [rbp-10h]
  unsigned __int64 v7; // [rsp+28h] [rbp-8h]

  v7 = __readfsqword(0x28u);
  v6 = fopen_err_log();
  if ( v6 )
  {
    v1 = -1;
    if ( (unsigned int)sub_402F45((int *)&v1) || (v4 = 0, v3 = sub_402DD5(v6, 15, &v4), v3 <= 0) )
    {
      sub_40327C(v6, v1, 0);
      result = 1;
    }
    else
    {
      v5 = 0;
      v2 = 0;
      if ( (unsigned int)sub_40302F(v4, (unsigned int)v3, &v5, &v2) )
      {
        sub_40327C(v6, v1, v4);
        result = 1;
      }
      else
      {
        if ( (unsigned int)sub_4031DF(v1, v5, v2) )
          perror("send");
        sub_40327C(v6, v1, v4);
        sub_5A74F0(v5);
        result = 0;
      }
    }
  }
  else
  {
    result = 1;
  }
  if ( __readfsqword(0x28u) != v7 )
    sub_5ED100();
  return result;
}

#+end_src

Видим что в функции есть 3 блока в зависимости от условий где возвращается 0 или 1 в каждом из случаев
v1 = -1
Зачем инициализировать переменную значением -1? Паттерн sentienel value когда значение false (или любое другое известно заранее вместо мусора) является базовым
пока явно не выполнится часть функции приводящая к измененному значению

в первом блоке встречаем функцию которую заметили в начале п.3, провалимся в нее
Можно обратить внимаение что входной параметр *a1 используется только в одном случае

В функции мы имеем структуру sockaddr
       #+begin_src C
       struct sockaddr {
                  sa_family_t     sa_family;      /* Address family */
                  char            sa_data[];      /* Socket address */
              };
       #+end_src

Но выглядит это как-то странно и разметка получилась кривая, гуглим что-почем и находим
sockaddr_in
shift+f1 -> add local type -> добавляем прототип -> меняем sockaddr на sockaddr_in -> M на sin_family и задаем enum AF_INET и проучаеися вот такая красота

        #+begin_src C
        int v2; // [rsp+1Ch] [rbp-24h]
                struct sockaddr_in v3; // [rsp+20h] [rbp-20h] BYREF
                unsigned __int64 v4; // [rsp+38h] [rbp-8h]

                v4 = __readfsqword(0x28u);
                *(_QWORD *)&v3.sin_family = AF_INET;
                *(_QWORD *)v3.sin_zero = 0;
                v3.sin_port = htons(0x2AEC);

        #+end_src

Насчет htons: приводит значение из le в be для приведения из процессорного вида к сетевому
реализован через ROL2(v, 8)
Который ротирует налево 8 байт значения, для 16 байт числа это как раз перевод младших битов к старшим и наоборот


#+begin_src python :results output
print(int("0x2AEC", 16))
#+end_src

#+RESULTS:
: 10988

Вот и порт, адрес лежал в открытом виде в строках
Ответ на 5: 10.38.190.16:10986

Перейдем к  sub_5F28A0(2, "10.38.190.16", (__m128i *)&sock.sin_addr);
Она большая, но сначала смотрим на макро структуру
Там есть диспетчеризация в зависимости от a1 - первого аргумента (мы передаем 2)
кейсы
        a1 == 2
        a1 != 10
 Второй не достигается, а для 2 у нас есть кандидат из первого это AF_INET + AF_INET6 это как раз 10

 В итоге остается
  #+begin_src C
    v4 = a2;
    v19 = __readfsqword(0x28u);
    v5 = sub_401110(a2);
    if ( arg1 == AF_INET )
    {
        result = sub_5F2570(a2, &a2[v5], a3);
        goto LABEL_4;
    }
  #+end_src

sub_5F2570 получает строку и конец строки??, тогда предположим result = sub_5F2570(arg2, &arg2[len], buf);

 #+begin_src C
 __INT64 __fastcall sub_5F2570(char *a1, char *a2, _DWORD *a3)
 {
   unsigned __int8 *v3; // r8
   int v4; // r10d
   int v5; // r9d
   int v6; // r11d
   unsigned int v7; // eax
   int v8; // eax
   __int64 result; // rax
   int v10; // [rsp+4h] [rbp-14h] BYREF
   unsigned __int64 v11; // [rsp+8h] [rbp-10h]

   v11 = __readfsqword(0x28u);
   LOBYTE(v10) = 0;
   if ( a1 >= a2 )
     goto LABEL_17;
   v3 = (unsigned __int8 *)&v10;
   v4 = 0;
   v5 = 0;
   do
   {
     while ( 1 )
     {
       v8 = *a1++;
       if ( (unsigned int)(v8 - 48) <= 9 )
         break;
       if ( ((unsigned __int8)v5 & (v8 == 46)) == 0 || v4 == 4 )
         goto LABEL_17;
       v3[1] = 0;
       v5 = 0;
       ++v3;
       if ( a2 == a1 )
         goto LABEL_12;
     }
     v6 = *v3;
     v7 = v8 - 48 + 10 * v6;
     if ( v5 )
     {
       if ( v7 > 0xFF || !(_BYTE)v6 )
         goto LABEL_17;
       ,*v3 = v7;
     }
     else
     {
       if ( v7 > 0xFF )
         goto LABEL_17;
       ++v4;
       ,*v3 = v7;
       if ( v4 > 4 )
         goto LABEL_17;
       v5 = 1;
     }
   }
   while ( a2 != a1 );
 LABEL_12:
   if ( v4 <= 3 )
   {
 LABEL_17:
     result = 0;
   }
   else
   {
     ,*a3 = v10;
     result = 1;
   }
   if ( __readfsqword(0x28u) != v11 )
     sub_5ED100();
   return result;
 }

#+end_src

Объявляется int v10;
Инициализируется младший байт нулем который
с помощью v3 мы по байту гуляем в 4 байту
Паттерн иды выделения места на стек для структуры и обращения к ее элементам


int v10; LOBYTE(v10) = 0; v3 = (unsigned __int8 *)&v10;
~ *((unsigned char *)&v10) = 0;
~ ((unsigned char *)&v10)[0] = 0;

Дальше идет проверка на адрес
if ( (unsigned int)(symbol - 48) <= 9 ) - проверка на 0-9
так как 48 это ascii 0
if ( ((unsigned __int8)v5 & (symbol == 46)) == 0 || v4 == 4 ) - проверка на .
так как 46 это ascii .
переименуем вот так
if ( ((unsigned __int8)hasDot & (symbol == 46)) == 0 || octet == 4 )
если в октете нет точки и это точека и это не 4 октет то все норм
Короче это валидация IPv4 и приведение его к бинарному значению
После добавления sockaddr_in и гугла который подсказал про контекст
мы находим connect, close, inet_pton и все вообще становится красиво
#+begin_src C
__int64 __fastcall connection(int *a1)
{
  __int64 result; // rax
  int sockfd; // [rsp+1Ch] [rbp-24h]
  struct sockaddr_in sock; // [rsp+20h] [rbp-20h] BYREF
  unsigned __int64 v4; // [rsp+38h] [rbp-8h]

  v4 = __readfsqword(0x28u);
  *(_QWORD *)&sock.sin_family = AF_INET;
  *(_QWORD *)sock.sin_zero = 0;
  sock.sin_port = htons(0x2AEC);
  inet_pton(2, "10.38.190.16", &sock.sin_addr);
  sockfd = socket(2, 1, 0);
  if ( sockfd >= 0 )
  {
    if ( connect(sockfd, (const struct sockaddr *)&sock, 0x10u) )
    {
      perror("connect");
      close(sockfd);
      result = 0xFFFFFFFFLL;
    }
    else
    {
      *a1 = sockfd;
      result = 0;
    }
  }
  else
  {
    perror("socket");
    result = 0xFFFFFFFFLL;
  }
  if ( __readfsqword(0x28u) != v4 )
    sub_5ED100();
  return result;
}
#+end_src

Мы получили ответы на вопросы о сетевом соединении
Идем назад и ищем где читается текст лога

#+begin_src C
__int64 __fastcall sub_402DD5(__int64 log_f, int a2, _QWORD *prob_buf)
{
  __int64 result; // rax
  unsigned int v5; // [rsp+24h] [rbp-11Ch]
  int i; // [rsp+28h] [rbp-118h]
  int v7; // [rsp+2Ch] [rbp-114h]
  _BYTE v8[264]; // [rsp+30h] [rbp-110h] BYREF
  unsigned __int64 v9; // [rsp+138h] [rbp-8h]

  v9 = __readfsqword(0x28u);
  v5 = 0;
  *prob_buf = sub_5A6F00(a2 << 8);
  if ( *prob_buf )
  {
    *(_BYTE *)*prob_buf = 0;
    for ( i = 0; i < a2 && sub_5966C0(v8, 256, log_f); ++i )
    {
      v7 = strlen((__int64)v8);
      j_ifunc_5AABF0((int)v5 + *prob_buf, v8, v7);
      v5 += v7;
    }
    result = v5;
  }
  else
  {
    result = 0xFFFFFFFFLL;
  }
  if ( __readfsqword(0x28u) != v9 )
    sub_5ED100();
  return result;
}

#+end_src

Из вызова функции мы знаем что a2 = 15, похоже на len и используется в цикле
a2 << 8 ~ a2 * 256 = 15*2^8=3840
Также a3 напоминает буфер
[[id:7290e042-4a03-4209-aeb3-4399e926d28b][malloc]]

В условии цикла есть помимо счетчика проверка на sub_5966C0(v8, 256, log_f)
что то что принимает v8, 256, *FILE и скорее всего возвращает неноль когда успешно
может буфер, длина, стрим?
[[id:34fb842e-7d15-4f6e-ae04-52374df17a17][fgets]]

То есть цикл останавливается или на 15 или когда fgets упадет

j_ifunc_5AABF0((int)v5 + *prob_buf, str, len);

ifunc = Indirect Function
индеректная функция выбирающая реализацию во время исполнения часто встречается для стандартной C библиотеки

Принимает int к которому прибавляет указателю, точнее смещает его на v5 который изначально равен 0 а потом длинне строки с каждой итерацией
короче смещает указатель на длинну строки в цикле

вся функция в итоге возвращает суммарную длинну

ну и получается что счетчик это счетчик строк
ответ 15

Кандидат на шифрование
#+begin_src C
__int64 __fastcall sub_40302F(__int64 a1, unsigned int full_len, __int64 *a3, _DWORD *a4)
{
  __int64 result; // rax
  __int64 v5; // rsi
  __int64 v6; // rax
  int v10; // [rsp+24h] [rbp-1Ch] BYREF
  int v11; // [rsp+28h] [rbp-18h]
  int v12; // [rsp+2Ch] [rbp-14h]
  __int64 v13; // [rsp+30h] [rbp-10h]
  unsigned __int64 v14; // [rsp+38h] [rbp-8h]

  v14 = __readfsqword(0x28u);
  v13 = sub_407160();
  if ( v13 )
  {
    v5 = sub_406A50();
    if ( (unsigned int)sub_408320(v13, v5, 0, &unk_651010, &unk_651020) == 1
      && (v6 = sub_406A50(), v11 = full_len + sub_408600(v6), (*a3 = malloc(v11)) != 0) )
    {
      v10 = 0;
      v12 = 0;
      if ( (unsigned int)sub_407510(v13, *a3, &v10, a1, full_len) == 1
        && (v12 = v10, (unsigned int)sub_407550(v13, *a3 + v10, &v10) == 1) )
      {
        v12 += v10;
        *a4 = v12;
        sub_407180(v13);
        result = 0;
      }
      else
      {
        sub_5A74F0(*a3);
        sub_407180(v13);
        result = 0xFFFFFFFFLL;
      }
    }
    else
    {
      sub_407180(v13);
      result = 0xFFFFFFFFLL;
    }
  }
  else
  {
    result = 0xFFFFFFFFLL;
  }
  if ( __readfsqword(0x28u) != v14 )
    sub_5ED100();
  return result;
}

#+end_src

И тут же есть
#+begin_src C
__int64 sub_407160()
{
  return sub_40C5B0(168, "../crypto/evp/evp_enc.c", 43);
}
#+end_src

Это относительный путь до openssl
[[id:7a6d2af2-f493-4ca8-97b1-93b0759e392b][EVP]]

Мы находим указатель на структуру sub_406A50();
Первое значение - nid, id алгоритма который равен 1A3 = 419 = AES-128-CBC

(unsigned int)sub_408320(v13, v5, 0, &unk_651010, &unk_651020) == 1
int EVP_EncryptInit_ex(EVP_CIPHER_CTX *ctx, const EVP_CIPHER *cipher,
                        ENGINE *impl, const unsigned char *key,
                        const unsigned char *iv);


**** Вопрос без ответа
- в ходе 3.1 IDA подхватила структуру sockaddr в первоначальной функции, но я не понял как и в какой момент
- __writefsdword(0xFFFFFFB0, ...) — это паттерн записи в errno через thread-local storage (на Linux errno часто реализован именно так, через FS-сегмент). А 0x61 = 97 в десятичном.  errno.h любой Linux-системы, 97 это код ошибки EAFNOSUPPORT ("Address family not supported").
