#+title: Practice Signature Magic Ball


#+begin_src shell :dir . :results output
ls signature/
#+end_src

#+RESULTS:
#+begin_example
assets
libjpeg-9.dll
libpng16-16.dll
libtiff-5.dll
libwebp-7.dll
Magic8Ball.exe
SDL2_image.dll
SDL2_ttf.dll
SDL2.dll
zlib1.dll
#+end_example

* TEMP
#+begin_src C
result = SDL_PollEvent(&v7);
if ( result )
{
    while ( v7.type <= SDL_KEYUP )              // KEY <= 0x301
    {
    switch ( v7.type )                        // SWITCH ot key
    {
        case SDL_KEYUP:                         // if KEY = KEYUP
        switch ( v7.window.data2 )            // data2 = /**< event dependent data */
        {
            case SDLK_RIGHT:
            if ( *(this + 359) )              // ~= *(this + N) = 0
                *(this + 359) = 0;
            break;
            case SDLK_LEFT:
            if ( *(this + 358) )
                *(this + 358) = 0;
            break;
            case SDLK_DOWN:
            if ( *(this + 357) )
                *(this + 357) = 0;
            break;
            case SDLK_UP:
            if ( *(this + 356) )
                *(this + 356) = 0;
            break;
            default:
            goto LABEL_40;
        }

#+end_src

Получается мы жмем кнопки и отбрасываем/обрабатываем?
#+begin_src C

while (key <= key_0x301){
   switch (key){ // v7,type ~ отвечает за то что за ивент произошел, в нашем случае KEYUP нажатие кнопки
       if (some_key) { // IDA назвала это v7.windows.data2 ~ отвечает за то какая именно KEYUP произошла
         some_flag = 0
        }
       if (some_key) {
         some_flag = 0
        }
       if (some_key) {
         some_flag = 0
        }
       default {
         goto next key if key else return result
       }
  }
}
#+end_src
 Этот паттерн выльется в логику блока

* objdump cheatsheet :objdump:
-d - disasssemble
0x004028cb
* Символы
#+begin_src shell :dir . :results output
babel-shell llvm-objdump -t signature/Magic8Ball.exe
#+end_src

#+RESULTS:
:
: signature/Magic8Ball.exe:	file format coff-i386
:
: SYMBOL TABLE:

#+begin_src shell :dir . :results output
babel-shell llvm-nm signature/Magic8Ball.exe
#+end_src

#+RESULTS:
: signature/Magic8Ball.exe: no symbols

* Дизасм
:PROPERTIES:
:ID:       b15ed8f9-edac-449d-84b4-389d10fb4552
:END:
#+begin_src shell :dir . :results output
babel-shell llvm-objdump -d signature/Magic8Ball.exe | grep "4028cb"
#+end_src

#+RESULTS:
:   4020a9: e8 1d 08 00 00               	calll	0x4028cb <.text+0x18cb>
:   402116: e8 b0 07 00 00               	calll	0x4028cb <.text+0x18cb>
:   4028cb: ff 25 d8 40 40 00            	jmpl	*0x4040d8

- Вызов функции инструкцией jump long

#+begin_src shell :dir . :results output
babel-shell objdump -x signature/Magic8Ball.exe | grep -A 40 "The Import Tables"
#+end_src

#+RESULTS:
#+begin_example
The Import Tables (interpreted .rdata section contents)
 vma:            Hint    Time      Forward  DLL       First
                 Table   Stamp     Chain    Name      Thunk
 00004ce4	00004ea4 00000000 00000000 00005150 00004080

	DLL Name: SDL2.dll
	vma:     Ordinal  Hint  Member-Name  Bound-To
	00004080  <none>  0328  SDL_wcslen
	00004084  <none>  0307  SDL_strlen
	00004088  <none>  02d7  SDL_iconv_string
	0000408c  <none>  0240  SDL_SetMainReady
	00004090  <none>  0041  SDL_Delay
	00004094  <none>  00fd  SDL_GetTicks
	00004098  <none>  01d5  SDL_Quit
	0000409c  <none>  02bf  SDL_free
	000040a0  <none>  0150  SDL_Init
	000040a4  <none>  0045  SDL_DestroyRenderer
	000040a8  <none>  0047  SDL_DestroyTexture
	000040ac  <none>  0211  SDL_RenderPresent
	000040b0  <none>  01ee  SDL_RenderCopy
	000040b4  <none>  01ed  SDL_RenderClear
	000040b8  <none>  0247  SDL_SetRenderDrawColor
	000040bc  <none>  0037  SDL_CreateTextureFromSurface
	000040c0  <none>  0031  SDL_CreateRenderer
	000040c4  <none>  01cf  SDL_PollEvent
	000040c8  <none>  0274  SDL_StartTextInput
	000040cc  <none>  0048  SDL_DestroyWindow
	000040d0  <none>  003a  SDL_CreateWindow
	000040d4  <none>  005d  SDL_FreeSurface
	000040d8  <none>  00c0  SDL_GetError
	000040dc  <none>  0270  SDL_ShowSimpleMessageBox

 00004cf8	00004f08 00000000 00000000 00005172 000040e4

	DLL Name: SDL2_image.dll
	vma:     Ordinal  Hint  Member-Name  Bound-To
	000040e4  <none>  0000  IMG_Init
	000040e8  <none>  0002  IMG_Load

 00004d0c	00004f14 00000000 00000000 000051d6 000040f0

#+end_example

#+begin_src shell :dir . :results output
babel-shell llvm-readobj --coff-imports signature/Magic8Ball.exe
#+end_src

#+RESULTS:
#+begin_example

File: signature/Magic8Ball.exe
Format: COFF-i386
Arch: i386
AddressSize: 32bit
Import {
  Name: SDL2.dll
  ImportLookupTableRVA: 0x4EA4
  ImportAddressTableRVA: 0x4080
  Symbol: SDL_wcslen (808)
  Symbol: SDL_strlen (775)
  Symbol: SDL_iconv_string (727)
  Symbol: SDL_SetMainReady (576)
  Symbol: SDL_Delay (65)
  Symbol: SDL_GetTicks (253)
  Symbol: SDL_Quit (469)
  Symbol: SDL_free (703)
  Symbol: SDL_Init (336)
  Symbol: SDL_DestroyRenderer (69)
  Symbol: SDL_DestroyTexture (71)
  Symbol: SDL_RenderPresent (529)
  Symbol: SDL_RenderCopy (494)
  Symbol: SDL_RenderClear (493)
  Symbol: SDL_SetRenderDrawColor (583)
  Symbol: SDL_CreateTextureFromSurface (55)
  Symbol: SDL_CreateRenderer (49)
  Symbol: SDL_PollEvent (463)
  Symbol: SDL_StartTextInput (628)
  Symbol: SDL_DestroyWindow (72)
  Symbol: SDL_CreateWindow (58)
  Symbol: SDL_FreeSurface (93)
  Symbol: SDL_GetError (192)
  Symbol: SDL_ShowSimpleMessageBox (624)
}
Import {
  Name: SDL2_image.dll
  ImportLookupTableRVA: 0x4F08
  ImportAddressTableRVA: 0x40E4
  Symbol: IMG_Init (0)
  Symbol: IMG_Load (2)
}
Import {
  Name: SDL2_ttf.dll
  ImportLookupTableRVA: 0x4F14
  ImportAddressTableRVA: 0x40F0
  Symbol: TTF_OpenFont (29)
  Symbol: TTF_RenderText_Solid_Wrapped (49)
  Symbol: TTF_Init (24)
  Symbol: TTF_RenderText_Solid (48)
}
Import {
  Name: MSVCP140.dll
  ImportLookupTableRVA: 0x4E70
  ImportAddressTableRVA: 0x404C
  Symbol: ?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEDD@Z (1332)
  Symbol: ?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QAEXH_N@Z (1221)
  Symbol: ?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAE_JPBD_J@Z (1249)
  Symbol: ?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEXXZ (580)
  Symbol: ??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z (262)
  Symbol: ?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@XZ (872)
  Symbol: ?cerr@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A (674)
  Symbol: ?put@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@D@Z (1121)
  Symbol: ?uncaught_exception@std@@YA_NXZ (1310)
  Symbol: ?_Xlength_error@std@@YAXPBD@Z (654)
  Symbol: ?_Xout_of_range@std@@YAXPBD@Z (655)
  Symbol: ?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QAEHD@Z (1246)
}
Import {
  Name: VCRUNTIME140.dll
  ImportLookupTableRVA: 0x4F30
  ImportAddressTableRVA: 0x410C
  Symbol: __std_exception_destroy (34)
  Symbol: _CxxThrowException (1)
  Symbol: __CxxFrameHandler3 (16)
  Symbol: memcpy (70)
  Symbol: memmove (71)
  Symbol: __std_exception_copy (33)
  Symbol: __current_exception (28)
  Symbol: __current_exception_context (29)
  Symbol: _except_handler4_common (53)
  Symbol: __std_terminate (35)
  Symbol: memset (72)
}
Import {
  Name: api-ms-win-crt-runtime-l1-1-0.dll
  ImportLookupTableRVA: 0x4F84
  ImportAddressTableRVA: 0x4160
  Symbol: _controlfp_s (29)
  Symbol: _seh_filter_exe (66)
  Symbol: terminate (106)
  Symbol: _crt_atexit (31)
  Symbol: _initialize_onexit_table (54)
  Symbol: _invalid_parameter_noinfo_noreturn (59)
  Symbol: _configure_narrow_argv (25)
  Symbol: _register_onexit_function (62)
  Symbol: _set_app_type (68)
  Symbol: _register_thread_local_exe_atexit_callback (63)
  Symbol: _c_exit (22)
  Symbol: _cexit (23)
  Symbol: _initialize_narrow_environment (53)
  Symbol: _exit (37)
  Symbol: exit (88)
  Symbol: _initterm_e (57)
  Symbol: _initterm (56)
  Symbol: _get_narrow_winmain_command_line (45)
}
Import {
  Name: api-ms-win-crt-string-l1-1-0.dll
  ImportLookupTableRVA: 0x4FDC
  ImportAddressTableRVA: 0x41B8
  Symbol: strncmp (142)
}
Import {
  Name: api-ms-win-crt-utility-l1-1-0.dll
  ImportLookupTableRVA: 0x4FEC
  ImportAddressTableRVA: 0x41C8
  Symbol: rand (27)
  Symbol: srand (29)
}
Import {
  Name: api-ms-win-crt-time-l1-1-0.dll
  ImportLookupTableRVA: 0x4FE4
  ImportAddressTableRVA: 0x41C0
  Symbol: _time64 (48)
}
Import {
  Name: api-ms-win-crt-heap-l1-1-0.dll
  ImportLookupTableRVA: 0x4F60
  ImportAddressTableRVA: 0x413C
  Symbol: _set_new_mode (22)
  Symbol: malloc (25)
  Symbol: free (24)
  Symbol: _callnewh (8)
}
Import {
  Name: api-ms-win-crt-math-l1-1-0.dll
  ImportLookupTableRVA: 0x4F7C
  ImportAddressTableRVA: 0x4158
  Symbol: __setusermatherr (46)
}
Import {
  Name: api-ms-win-crt-stdio-l1-1-0.dll
  ImportLookupTableRVA: 0x4FD0
  ImportAddressTableRVA: 0x41AC
  Symbol: _set_fmode (84)
  Symbol: __p__commode (1)
}
Import {
  Name: api-ms-win-crt-locale-l1-1-0.dll
  ImportLookupTableRVA: 0x4F74
  ImportAddressTableRVA: 0x4150
  Symbol: _configthreadlocale (8)
}
Import {
  Name: KERNEL32.dll
  ImportLookupTableRVA: 0x4E24
  ImportAddressTableRVA: 0x4000
  Symbol: UnhandledExceptionFilter (1457)
  Symbol: SetUnhandledExceptionFilter (1393)
  Symbol: GetCurrentProcess (538)
  Symbol: TerminateProcess (1424)
  Symbol: IsProcessorFeaturePresent (905)
  Symbol: QueryPerformanceCounter (1103)
  Symbol: GetCurrentProcessId (539)
  Symbol: GetCurrentThreadId (543)
  Symbol: GetSystemTimeAsFileTime (748)
  Symbol: InitializeSListHead (870)
  Symbol: IsDebuggerPresent (898)
  Symbol: GetStartupInfoW (723)
  Symbol: GetModuleHandleW (635)
  Symbol: GetCommandLineW (474)
  Symbol: HeapAlloc (840)
  Symbol: GetProcessHeap (695)
  Symbol: LocalFree (979)
  Symbol: HeapFree (844)
}
Import {
  Name: SHELL32.dll
  ImportLookupTableRVA: 0x4F28
  ImportAddressTableRVA: 0x4104
  Symbol: CommandLineToArgvW (8)
}
#+end_example


* IDA :ida:reverse:
:PROPERTIES:
:ID:       28cc51e9-cdf1-4e42-bbc0-bf9abe1a9dfd
:END:
Алгоритм: что делать когда видишь подозрение на библиотечную функцию

1. Распознай признак
Смотришь на вызов и видишь имя начинающееся с SDL_, TTF_, IMG_, или просто незнакомое имя функции из системной библиотеки.
#+begin_src C
TextureFromSurface = SDL_CreateTextureFromSurface(renderer, surface);
#+end_src
2. Проверь - это уже подгруженная сигнатура, или sub_XXXXXX?
Если функция называется человеческим именем (SDL_CreateTextureFromSurface) - IDA уже её узнала, сигнатура подгружена. Переходи к шагу 4.
Если видишь sub_401234 рядом с вызовами SDL-объектов - возможно это библиотечная функция, которую IDA не распознала по имени.

3. (Если sub_XXXXXX) Найди сигнатуру вручную
Погугли: <имя похожей функции> signature или посмотри на параметры (сколько их, какие типы) и поищи в SDL2 docs функцию с похожей сигнатурой
Или: правый клик на функции → Set function type → если знаешь сигнатуру, впиши её руками

4. Прочитай сигнатуру - не лезь внутрь
Наведи курсор на функцию или глянь в SDL2 wiki:
#+begin_src C
SDL_Texture* SDL_CreateTextureFromSurface(SDL_Renderer* renderer, SDL_Surface* surface);
#+end_src
Теперь ты знаешь: принимает рендерер и поверхность, возвращает текстуру. Этого достаточно - не открывай саму функцию, она внутри SDL.dll/.so, реверсить её бессмысленно.
5. Используй сигнатуру чтобы понять контекст вызова
#+begin_src C
TextureFromSurface = SDL_CreateTextureFromSurface(*(SDL_Renderer **)(this + 8), result);
#+end_src
Раз первый параметр - SDL_Renderer*, значит *(this+8) это рендерер. Сразу понятен смысл смещения +8 в твоей структуре - это поле renderer.
6. Сразу применяй открытие к структуре
Иди в Local Types, добавляй:
#+begin_src C
SDL_Renderer* renderer;  // offset 8
#+end_src

G -> 004028cb
G -> 0040227b -> google

===
Download SDL
File -> Load -> Parce C header file -> SDL.h
Y -> type
M -> enum

** Инфа по SDL2
*** SDL_Event
#+begin_src C
typedef union SDL_Event
{
    Uint32 type;                            /**< Event type, shared with all events */
    SDL_CommonEvent common;                 /**< Common event data */
    SDL_DisplayEvent display;               /**< Display event data */
    SDL_WindowEvent window;                 /**< Window event data */
    SDL_KeyboardEvent key;                  /**< Keyboard event data */
    SDL_TextEditingEvent edit;              /**< Text editing event data */
    SDL_TextEditingExtEvent editExt;        /**< Extended text editing event data */
    SDL_TextInputEvent text;                /**< Text input event data */
    SDL_MouseMotionEvent motion;            /**< Mouse motion event data */
    SDL_MouseButtonEvent button;            /**< Mouse button event data */
    SDL_MouseWheelEvent wheel;              /**< Mouse wheel event data */
    SDL_JoyAxisEvent jaxis;                 /**< Joystick axis event data */
    SDL_JoyBallEvent jball;                 /**< Joystick ball event data */
    SDL_JoyHatEvent jhat;                   /**< Joystick hat event data */
    SDL_JoyButtonEvent jbutton;             /**< Joystick button event data */
    SDL_JoyDeviceEvent jdevice;             /**< Joystick device change event data */
    SDL_JoyBatteryEvent jbattery;           /**< Joystick battery event data */
    SDL_ControllerAxisEvent caxis;          /**< Game Controller axis event data */
    SDL_ControllerButtonEvent cbutton;      /**< Game Controller button event data */
    SDL_ControllerDeviceEvent cdevice;      /**< Game Controller device event data */
    SDL_ControllerTouchpadEvent ctouchpad;  /**< Game Controller touchpad event data */
    SDL_ControllerSensorEvent csensor;      /**< Game Controller sensor event data */
    SDL_AudioDeviceEvent adevice;           /**< Audio device event data */
    SDL_SensorEvent sensor;                 /**< Sensor event data */
    SDL_QuitEvent quit;                     /**< Quit request event data */
    SDL_UserEvent user;                     /**< Custom event data */
    SDL_SysWMEvent syswm;                   /**< System dependent window event data */
    SDL_TouchFingerEvent tfinger;           /**< Touch finger event data */
    SDL_MultiGestureEvent mgesture;         /**< Gesture event data */
    SDL_DollarGestureEvent dgesture;        /**< Gesture event data */
    SDL_DropEvent drop;                     /**< Drag and drop event data */

    /* This is necessary for ABI compatibility between Visual C++ and GCC.
       Visual C++ will respect the push pack pragma and use 52 bytes (size of
       SDL_TextEditingEvent, the largest structure for 32-bit and 64-bit
       architectures) for this union, and GCC will use the alignment of the
       largest datatype within the union, which is 8 bytes on 64-bit
       architectures.

       So... we'll add padding to force the size to be 56 bytes for both.

       On architectures where pointers are 16 bytes, this needs rounding up to
       the next multiple of 16, 64, and on architectures where pointers are
       even larger the size of SDL_UserEvent will dominate as being 3 pointers.
    */
    Uint8 padding[sizeof(void *) <= 8 ? 56 : sizeof(void *) == 16 ? 64 : 3 * sizeof(void *)];
} SDL_Event;

#+end_src

- SDL_Event это union - структура где все поля начинаются с одного адреса
  В зависимости от того откуда мы читаем одни и те же байты берут разные имена
  Есть инфа что ида может ошибиться и дать имя относительно не того объекта ??

  Условная память SDL_Event :

    Байты:  [0  1  2  3] [4  5  6  7] [8  9  10  11] ...
            |___________|
                ↑
            .type (Uint32, 4 байта) -  поле, есть у всех событий

            |___________|____________|_______________|
                ↑            ↑              ↑
            key.type    key.scancode   key.sym (код клавиши)

            |___________|____________|_______________|
                ↑            ↑              ↑
            window.type  window.windowID  window.data1 ...window.data2

*** SDL_EventType
#+begin_src C
typedef enum SDL_EventType
{
    SDL_FIRSTEVENT     = 0,     /**< Unused (do not remove) */

    /* Application events */
    SDL_QUIT           = 0x100, /**< User-requested quit */

    /* These application events have special meaning on iOS, see README-ios.md for details */
    SDL_APP_TERMINATING,        /**< The application is being terminated by the OS
                                     Called on iOS in applicationWillTerminate()
                                     Called on Android in onDestroy()
                                */
    SDL_APP_LOWMEMORY,          /**< The application is low on memory, free memory if possible.
                                     Called on iOS in applicationDidReceiveMemoryWarning()
                                     Called on Android in onLowMemory()
                                */
    SDL_APP_WILLENTERBACKGROUND, /**< The application is about to enter the background
                                     Called on iOS in applicationWillResignActive()
                                     Called on Android in onPause()
                                */
    SDL_APP_DIDENTERBACKGROUND, /**< The application did enter the background and may not get CPU for some time
                                     Called on iOS in applicationDidEnterBackground()
                                     Called on Android in onPause()
                                */
    SDL_APP_WILLENTERFOREGROUND, /**< The application is about to enter the foreground
                                     Called on iOS in applicationWillEnterForeground()
                                     Called on Android in onResume()
                                */
    SDL_APP_DIDENTERFOREGROUND, /**< The application is now interactive
                                     Called on iOS in applicationDidBecomeActive()
                                     Called on Android in onResume()
                                */

    SDL_LOCALECHANGED,  /**< The user's locale preferences have changed. */

    /* Display events */
    SDL_DISPLAYEVENT   = 0x150,  /**< Display state change */

    /* Window events */
    SDL_WINDOWEVENT    = 0x200, /**< Window state change */
    SDL_SYSWMEVENT,             /**< System specific event */

    /* Keyboard events */
    SDL_KEYDOWN        = 0x300, /**< Key pressed */
    SDL_KEYUP,                  /**< Key released */
    SDL_TEXTEDITING,            /**< Keyboard text editing (composition) */
    SDL_TEXTINPUT,              /**< Keyboard text input */
    SDL_KEYMAPCHANGED,          /**< Keymap changed due to a system event such as an
                                     input language or keyboard layout change.
                                */
    SDL_TEXTEDITING_EXT,       /**< Extended keyboard text editing (composition) */

    /* Mouse events */
    SDL_MOUSEMOTION    = 0x400, /**< Mouse moved */
    SDL_MOUSEBUTTONDOWN,        /**< Mouse button pressed */
    SDL_MOUSEBUTTONUP,          /**< Mouse button released */
    SDL_MOUSEWHEEL,             /**< Mouse wheel motion */

    /* Joystick events */
    SDL_JOYAXISMOTION  = 0x600, /**< Joystick axis motion */
    SDL_JOYBALLMOTION,          /**< Joystick trackball motion */
    SDL_JOYHATMOTION,           /**< Joystick hat position change */
    SDL_JOYBUTTONDOWN,          /**< Joystick button pressed */
    SDL_JOYBUTTONUP,            /**< Joystick button released */
    SDL_JOYDEVICEADDED,         /**< A new joystick has been inserted into the system */
    SDL_JOYDEVICEREMOVED,       /**< An opened joystick has been removed */
    SDL_JOYBATTERYUPDATED,      /**< Joystick battery level change */

    /* Game controller events */
    SDL_CONTROLLERAXISMOTION  = 0x650, /**< Game controller axis motion */
    SDL_CONTROLLERBUTTONDOWN,          /**< Game controller button pressed */
    SDL_CONTROLLERBUTTONUP,            /**< Game controller button released */
    SDL_CONTROLLERDEVICEADDED,         /**< A new Game controller has been inserted into the system */
    SDL_CONTROLLERDEVICEREMOVED,       /**< An opened Game controller has been removed */
    SDL_CONTROLLERDEVICEREMAPPED,      /**< The controller mapping was updated */
    SDL_CONTROLLERTOUCHPADDOWN,        /**< Game controller touchpad was touched */
    SDL_CONTROLLERTOUCHPADMOTION,      /**< Game controller touchpad finger was moved */
    SDL_CONTROLLERTOUCHPADUP,          /**< Game controller touchpad finger was lifted */
    SDL_CONTROLLERSENSORUPDATE,        /**< Game controller sensor was updated */
    SDL_CONTROLLERUPDATECOMPLETE_RESERVED_FOR_SDL3,
    SDL_CONTROLLERSTEAMHANDLEUPDATED,  /**< Game controller Steam handle has changed */

    /* Touch events */
    SDL_FINGERDOWN      = 0x700,
    SDL_FINGERUP,
    SDL_FINGERMOTION,

    /* Gesture events */
    SDL_DOLLARGESTURE   = 0x800,
    SDL_DOLLARRECORD,
    SDL_MULTIGESTURE,

    /* Clipboard events */
    SDL_CLIPBOARDUPDATE = 0x900, /**< The clipboard or primary selection changed */

    /* Drag and drop events */
    SDL_DROPFILE        = 0x1000, /**< The system requests a file open */
    SDL_DROPTEXT,                 /**< text/plain drag-and-drop event */
    SDL_DROPBEGIN,                /**< A new set of drops is beginning (NULL filename) */
    SDL_DROPCOMPLETE,             /**< Current set of drops is now complete (NULL filename) */

    /* Audio hotplug events */
    SDL_AUDIODEVICEADDED = 0x1100, /**< A new audio device is available */
    SDL_AUDIODEVICEREMOVED,        /**< An audio device has been removed. */

    /* Sensor events */
    SDL_SENSORUPDATE = 0x1200,     /**< A sensor was updated */

    /* Render events */
    SDL_RENDER_TARGETS_RESET = 0x2000, /**< The render targets have been reset and their contents need to be updated */
    SDL_RENDER_DEVICE_RESET, /**< The device has been reset and all textures need to be recreated */

    /* Internal events */
    SDL_POLLSENTINEL = 0x7F00, /**< Signals the end of an event poll cycle */

    /** Events SDL_USEREVENT through SDL_LASTEVENT are for your use,
     *  and should be allocated with SDL_RegisterEvents()
     */
    SDL_USEREVENT    = 0x8000,

    /**
     *  This last event is only for bounding internal arrays
     */
    SDL_LASTEVENT    = 0xFFFF
} SDL_EventType;

#+end_src

*** SDL_WindowEvent
#+begin_src C
typedef struct SDL_WindowEvent
{
    Uint32 type;        /**< SDL_WINDOWEVENT */
    Uint32 timestamp;   /**< In milliseconds, populated using SDL_GetTicks() */
    Uint32 windowID;    /**< The associated window */
    Uint8 event;        /**< SDL_WindowEventID */
    Uint8 padding1;
    Uint8 padding2;
    Uint8 padding3;
    Sint32 data1;       /**< event dependent data */
    Sint32 data2;       /**< event dependent data */
} SDL_WindowEvent;

#+end_src

** Псевдокомментарии
#+begin_src C
SDL_KEYUP,                  /**< Key released */
#+end_src

По __thiscall понимаем что это метод C++ класса
В теле много обращений по смещениям относительно this которые приводятся к разным типам
Вероятно ход от this по смещениям чтобы собрать структуру

- _фан факт_1_: объект имеющий структуру лежит в куче, в this хранится адрес начала объекта в памяти
смещения от начала объекта к полям фиксированы для типа объекта а не для экземпляра
*(this + N) ~ (this->field) и N не изменяется для всех экземпляров

- получается в функции есть локальная переменная v7 типа SDL_Event, SDL_PollEvent берет событие по адресу &v7 и начинается цикл while который работает пока есть события подходящего типа (type <= SDL_KEYUP) и проходит итерации свитчей которые запускают обработки

# 72;9M
- _фан факт_2_: есть два участка кода которые обращаются по смещению +344 от this и пишут туда объекты разных типов
 Подозреваю что в случае с WORD ему все равно на старший 345=1 и он просто хотел записать 0 в 344, но я не понял зачем так делать
#+begin_src C
{
                v3 = this + 248;
                v4 = *((_DWORD *)this + 66) - 1;
                *((_DWORD *)this + 66) = v4;
                if ( *((_DWORD *)this + 67) >= 0x10u )
                v3 = *(char **)v3;
                v3[v4] = 0;
LABEL_39:
                *(this + 344) = 1;
            }
            }

#+end_src
#+begin_src asm
.text:00401EC4                 mov     word ptr [esi+158h], 100h // esi+158h ~~ this+344
#+end_src#+begin_src C
if ( v7.window.data2 != SDLK_BACKSPACE )
            {
            if ( v7.window.data2 == 13 )
                *((_WORD *)this + 172) = 256;   // WORD = 2b = +344b и в 334 пойдет 0 а в старший 345 пойдет 1?
            break;
            }

#+end_src

- Смотрим следующие блоки
  #+begin_src C
  if ( *((_DWORD *)this + 66) ) // условие на 4 байтный объект по смещению 66*4=264 от this != 0
  {
      v3 = this + 248;
      v4 = *((_DWORD *)this + 66) - 1;
      *((_DWORD *)this + 66) = v4;
      if ( *((_DWORD *)this + 67) >= 0x10u )
          v3 = (_DWORD *)*v3;
      *((_BYTE *)v3 + v4) = 0;
  LABEL_39:
      *(this + 344) = 1;
  }
  #+end_src


- Составляем структуру
#+begin_src C
struct MagBallGameState {
    bool is_alive;       // offset 0
    char gap1[355];
    bool key_up;          // offset 356  (SDLK_UP)
    bool key_down;        // offset 357  (SDLK_DOWN)
    bool key_left;         // offset 358  (SDLK_LEFT)
    bool key_right;        // offset 359  (SDLK_RIGHT)
};
#+end_src
[[http://wiki.libsdl.org/SDL2/SDL_Event][SDL_Event Doc]]

SDL_events.h:
    #+begin_src C
    /* Keyboard events */
        SDL_KEYDOWN        = 0x300, /**< Key pressed */
        SDL_KEYUP,                  /**< Key released */
        SDL_TEXTEDITING,            /**< Keyboard text editing (composition) */
        SDL_TEXTINPUT,              /**< Keyboard text input */
        SDL_KEYMAPCHANGED,          /**< Keymap changed due to a system event such as an

    /* Application events */
        SDL_QUIT           = 0x100, /**< User-requested quit */
    #+end_src

    Есть вот такой кейс

    #+begin_src C
    case 0x100u: // SDL_QUIT
            *this = 0;
            break;
    #+end_src
*this = первый байт структуры
Получается первый элемент структуры это что-то типо флага 0~QUIT

View → Open Subviews → Local types (shift+f1)
Add type - и получаем



#+begin_src ERROR
67:9 warning '_M_IX86' macro redefined
433:9 warning previous definition is here
1:26 error expected unqualified-id
#+end_src
** Псевдокод

~raw
,#+begin_src C
int __thiscall sub_401E50(char *this)
{
  int result; // eax
  _DWORD *v3; // eax
  int v4; // ecx
  _DWORD *v5; // edi
  unsigned int v6; // edx
  SDL_Event v7; // [esp+8h] [ebp-3Ch] BYREF

  result = SDL_PollEvent(&v7);
  if ( result )
  {
    while ( v7.type <= 0x301 ) // M -> choose SDL ENUM => SDL_KEYUP
    {
      switch ( v7.type )
      {
        case 0x301u:  // SDL_KEYUP enum
          switch ( v7.window.data2 )
          {
            case 0x4000004F:
              if ( *(this + 359) )
                *(this + 359) = 0;
              break;
            case 0x40000050:
              if ( *(this + 358) )
                *(this + 358) = 0;
              break;
            case 0x40000051:
              if ( *(this + 357) )
                *(this + 357) = 0;
              break;
            case 0x40000052:
              if ( *(this + 356) )
                *(this + 356) = 0;
              break;
            default:
              goto LABEL_40;
          }
          break;
        case 0x100u: // SDL_QUIT
          *this = 0;
          break;
        case 0x300u: // SDL_KEYDOWN
          if ( v7.window.data2 > 1073741903 )
          {
            switch ( v7.window.data2 )
            {
              case 0x40000050:
                *(this + 358) = 1;
                break;
              case 0x40000051:
                *(this + 357) = 1;
                break;
              case 0x40000052:
                *(this + 356) = 1;
                break;
            }
            break;
          }
          if ( v7.window.data2 == 1073741903 )
          {
            *(this + 359) = 1;
          }
          else
          {
            if ( v7.window.data2 != 8 )
            {
              if ( v7.window.data2 == 13 )
                *((_WORD *)this + 172) = 256;
              break;
            }
            if ( *((_DWORD *)this + 66) )
            {
              v3 = this + 248;
              v4 = *((_DWORD *)this + 66) - 1;
              *((_DWORD *)this + 66) = v4;
              if ( *((_DWORD *)this + 67) >= 0x10u )
                v3 = (_DWORD *)*v3;
              *((_BYTE *)v3 + v4) = 0;
LABEL_39:
              *(this + 344) = 1;
            }
          }
          break;
      }
LABEL_40:
      result = SDL_PollEvent(&v7);
      if ( !result )
        return result;
    }
    if ( v7.type != 771 || v7.display.padding1 )
      goto LABEL_40;
    v5 = this + 248;
    sub_401780(this + 248, &v7.jaxis.axis, strlen(v7.edit.text));
    if ( *((_DWORD *)this + 66) > 0x4Bu )
    {
      v6 = *((_DWORD *)this + 66);
      if ( v6 < 0x4B )
        sub_401710();
      if ( *((_DWORD *)this + 67) >= 0x10u )
        v5 = (_DWORD *)*v5;
      *((_DWORD *)this + 66) = 75;
      memmove((char *)v5 + 75, (char *)v5 + v6, 1u);
    }
    goto LABEL_39;
  }
  return result;
}
#+end_src
* Важный предытог
Разбираться с функцией обрабатывающей PollEvent крайне интересно и относительно полезно, но по пути того как появляется понимание ее работы появляется понимание что не она отвечает за логику ответа, и изначально присвоиное название handler было правильным, но мне нужен не хендлер, поэтому дропаем и идем дальше к функции дающей ответ

Пройдясь по строкам нашел функцию которая содержит базовые ответы -> xref и приходим к main loop игры -> в нем находим хендлер и функцию идущую после него, в ней явно есть обработка каких-то значений и это уже больше похоже на кандидата для исследования
* Таргет функция (?)
Тут есть последовательность LLURULDUL что-то типо конами и потом strncmp
  #+begin_src C
  if ( *(_BYTE *)(this + 345) )
    {
      result = (SDL_Surface *)v4[5];
      v12 = v4;
      if ( (unsigned int)result >= 0x10 )
        v12 = (_BYTE *)*v4;
      if ( *v12 == 'L' )
      {
        v13 = v4;
        if ( (unsigned int)result >= 0x10 )
          v13 = (_BYTE *)*v4;
        if ( v13[1] == 'L' )
        {
          v14 = v4;
          if ( (unsigned int)result >= 0x10 )
            v14 = (_BYTE *)*v4;
          if ( v14[2] == 'U' )
          {
            v15 = v4;
            if ( (unsigned int)result >= 0x10 )
              v15 = (_BYTE *)*v4;
            if ( v15[3] == 'R' )
            {
              v16 = v4;
              if ( (unsigned int)result >= 0x10 )
                v16 = (_BYTE *)*v4;
              if ( v16[4] == 'U' )
              {
                v17 = v4;
                if ( (unsigned int)result >= 0x10 )
                  v17 = (_BYTE *)*v4;
                if ( v17[5] == 'L' )
                {
                  v18 = v4;
                  if ( (unsigned int)result >= 0x10 )
                    v18 = (_BYTE *)*v4;
                  if ( v18[6] == 'D' )
                  {
                    v19 = v4;
                    if ( (unsigned int)result >= 0x10 )
                      v19 = (_BYTE *)*v4;
                    if ( v19[7] == 'U' )
                    {
                      v20 = v4;
                      if ( (unsigned int)result >= 0x10 )
                        v20 = (_BYTE *)*v4;
                      if ( v20[8] == 'L' )
                      {
                        v21 = (const char *)(this + 248);
                        if ( *(_DWORD *)(this + 268) >= 0x10u )
                          v21 = *(const char **)v21;
                        result = (SDL_Surface *)strncmp(v21, (const char *)(this + 92), 0xFu);
                        if ( !result )
                        {
                          sub_401220(v4);
                          return (SDL_Surface *)sub_401A10(v22, v23, v24, v25, v26, v27);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  #+end_src

strncmp сравнивает ввод с 15 символами которые лежат в (const char *)(this + 92)

ищем что за this + 92, мы знаем два факта из предыдущего анализа - this + N статична и this = edi
сначала ищем конструктор, может в нем есть что-то
в main loop была функция перед которой освободается память и чет инициируется
  #+begin_src C
  v0 = operator new(0x174u);
    v1 = v0;
    if ( v0 )
    {
      memset(v0, 0, 0x174u);
      v2 = sub_4012B0(v1);
    }
    else
    {
      v2 = nullptr;
    }
  #+end_src
Заходим и ничего не находим по смещению +92
Дальше пробуем дизасм -> alt+t [edi+5Ch]
и находим
#+begin_src asm
.text:004021A1                 mov     dword ptr [edi+5Ch], 6D6D6967h
.text:004021A8                 mov     dword ptr [edi+60h], 6C662065h
.text:004021AF                 mov     dword ptr [edi+64h], 70206761h
.text:004021B6                 mov     dword ptr [edi+68h], 3F736Ch
#+end_src

~dida

6D6D6967h
6C662065h
70206761h
3F736Ch
Это lil endian -> 0x67696D6D 0x6520666C 0x61672070 0x3F736C

Получается
LLURULDUL +
gimme flag pls?

  U_cRackeD_th1$_maG1 cBaLLA_@flare-on.com

** spoiler
  SDL_GetError
  SDL_Texture * SDL_CreateTextureFromSurface(SDL_Renderer * renderer, SDL_Surface * surface);
  SDL_PollEvent
  LLURULDUL
  U_cRackeD_th1$_maG1cBaLL_!!_@flare-on.com
