#+title: M2 Analyze

* Минимальный набор перед анализом
Архитектура процессора - ARM, MIPS, x86, RISC-V и другие.
Структура памяти - расположение загрузчика, ядра, файловой системы и данные
Точка входа - адрес, с которого начинается выполнение кода.

* Определение базового адреса загрузки

- Binbloom - анализирует частоту встречаемости адресов и предсказывает смещение.
- BaseFind - ищет указатели в коде и вычисляет базовый адрес статистически.
- Ручной анализ - поиск в HEX-редакторе адресов, которые выглядят как указатели (например, 0x80001000).

* Примитивы RTOS/bare-metal
- RTOS
Идем из common sense: должен выполняться некий код -> задачи/потоки, должен быть обмен информацинй -> i/o, мьютексы, очереди, это должно где-то храниться - память

+ Характерные параметры задачи - указатель на основную функцию, имя (для rtos характерен приоритет) и подобные параметры
#+begin_src C
// FreeRTOS
xTaskCreate(vNetworkTask, "Net", 1024, NULL, 4, NULL);

// ThreadX
// Здесь: "App Server Thread" - название, nx_server_thread_entry - основная функция, pointer - указатель на стек
ret = tx_thread_create(&AppServerThread, "App Server Thread", nx_server_thread_entry, 0, pointer, 2 * DEFAULT_MEMORY_SIZE,  DEFAULT_PRIORITY, DEFAULT_PRIORITY, TX_NO_TIME_SLICE, TX_DONT_START);
#+end_src

+ Семафоры/Мьютексы обычно реализуются паттернами
  + Создание семафора (мьютекса) и размещение его дескриптора в глобальной памяти.
  + Переключение семафора/блокировка мьютекса перед критическим кодом или в начале функции.
  + Обратное переключение семафора/разблокировка мьютекса после критического кода или в конце функции.
#+begin_src C
// FreeRTOS (двоичный семафор)
SemaphoreHandle_t adc_sem = xSemaphoreCreateBinary();
xSemaphoreTake(smphrHandle, portMAX_DELAY);
txStatus = xSemaphoreGiveFromISR(smphrHandle, &xHigherPriorityTaskWoken);

// ThreadX (счетный семафор)
TX_SEMAPHORE file_sem;
tx_semaphore_create(&file_sem, "File Access", 3);
tx_semaphore_get(&file_sem, TX_WAIT_FOREVER);
tx_semaphore_put(&file_sem);
// FreeRTOS
SemaphoreHandle_t can_mutex = xSemaphoreCreateMutex();
xSemaphoreTake(can_mutex, portMAX_DELAY);
xSemaphoreGive(can_mutex);

// ThreadX
TX_MUTEX spi_mutex;
tx_mutex_create(&spi_mutex, "SPI Mutex", TX_INHERIT);
tx_mutex_get(&spi_mutex, TX_WAIT_FOREVER);
tx_mutex_put(&spi_mutex);
#+end_src

+ Очереди сообщений
  + Создание очереди и размещение ее дескриптора в глобальной области памяти.
  + Функция-отправитель в конце своей работы размещает сообщение, используя указанный дескриптор.
  + Функция-обработчик в начале своей работы извлекает сообщение, используя указанный дескриптор.

#+begin_src C
// FreeRTOS
// Здесь 5 — размер очереди
QueueHandle_t cmd_queue = xQueueCreate(5, sizeof(command_t));
xQueueSend(cmd_queue, &cmd, 0);
...
xQueueReceive(cmd_queue, &cmd, 500);

// ThreadX
TX_QUEUE RoutineQueue;
tx_queue_create(&RoutineQueue, "RoutineQueue", MESSAGE_SIZE, RoutineQueue_ptr, QUEUE_SIZE);
tx_queue_send(&RoutineQueue, &DispatcherMessage, TX_WAIT_FOREVER);
...
tx_queue_receive(&RoutineQueue, &RoutineMessage, TX_WAIT_FOREVER);
#+end_src

+ Примой доступ к I/O
  Взаимодействие с переферией по протоколам происходит через регистры отображаемые в адресное пространство
  Регистры в данном случае это область памяти связанная с конкретным устройством
Работа с периферией включает в себя:
- Конфигурацию регистров: установку режимов работы, скоростей, прерываний.
- Чтение состояний: проверку флагов готовности данных/устройств.
- Запись данных: непосредственную передачу в регистры данных.
- Обработку прерываний: реакцию на аппаратные события.

Например, в STM32F4:
- APB1/APB2 шины: периферия с разными скоростями;
- 0x40000000-0x5FFFFFFF: диапазон периферийных регистров;
- GPIOA: базовый адрес 0x40020000;
- USART1: базовый адрес 0x40011000.


** UART пример

#+begin_src C
UART_HandleTypeDef huart1;            // 1. Дескриптор UART
MX_USART1_UART_Init();                // 2. Функция инициализации

uint8_t rx_buf[10] = {0};             // Буфер для приёма (10 байт)
uint8_t tx_buf[10] = {0};             // Буфер для передачи (10 байт)

// 3. Отправить 10 байт из tx_buf через UART с таймаутом 100 мс
HAL_UART_Transmit(&huart1, tx_buf, 10, 100);

// 4. Принять 10 байт в rx_buf с таймаутом 5000 мс
HAL_UART_Receive(&huart1, rx_buf, 10, 5000);
#+end_src


#+begin_src C
huart->Instance = USART2;                             // Какой аппаратный UART используем (USART2)
huart->Init.BaudRate = 115200;                        // Скорость 115200 бит/с
huart->Init.WordLength = UART_WORDLENGTH_8B;          // 8 бит данных
huart->Init.StopBits = UART_STOPBITS_1;               // 1 стоп-бит
huart->Init.Parity = UART_PARITY_NONE;                // Без контроля чётности
huart->Init.Mode = UART_MODE_TX_RX;                   // Полный дуплекс (и приём, и передача)
huart->Init.HwFlowCtl = UART_HWCONTROL_NONE;          // Без аппаратного управления потоком (RTS/CTS)
huart->Init.OverSampling = UART_OVERSAMPLING_16;      // 16-кратная дискретизация (стандарт)
#+end_src


** Таймеры

Иногда может быть неясно, что стало причиной запуска той или иной функции в прошивке. В таких случаях стоит поискать связанные с ними таймеры.
запуск таймера зачастую требует имя, указатель на функцию-обработчик и числовые параметры

#+begin_src C
// FreeRTOS
TimerHandle_t  xExampleSoftwareTimer = xTimerCreate(( const char * ) "LEDTimer", 500, pdTRUE, ( void * ) 0, led_timer_callback );
xTimerStart( xExampleSoftwareTimer, 0 );

// ThreadX
TX_TIMER led_timer;
tx_timer_create(&led_timer, "led_timer", led_timer_callback, 0x1234, 200, 200, TX_AUTO_ACTIVATE);

#+end_src

** Примитивы Linux-подобных систем
- U-Boot: окружение загрузки
#+begin_src shell
> printenv
bootcmd=mmc dev 0; ext4load mmc 0:1 0x82000000 zImage; bootz 0x82000000
bootargs=console=ttymxc0,115200 root=/dev/mmcblk0p2 rootwait
#+end_src

- Systemd: управление сервисами
  хорошая точка входа для определения полезной нагрузки прошивки.

Пример VPN-шлюза:
#+begin_src shell
# /etc/systemd/system/wireguard.service
[Unit]
Requires=network.target
After=firewall.service

[Service]
ExecStartPre=/usr/bin/wg genkey > /etc/wg/private.key
ExecStart=/usr/bin/wg-quick up wg0
RestartSec=5

[Install]
WantedBy=multi-user.target
#+end_src

- Fstab: монтирование ФС

файл /etc/fstab. В нем определяются точки монтирования и параметры файловых систем.

Пример:

#+begin_src shell
/dev/mmcblk0p1  /          ext4  ro,noatime,errors=remount-ro  0 1
/dev/mmcblk0p2  /media     ext4  rw,noexec,data=journal        0 2
tmpfs           /tmp       tmpfs size=64M,mode=1777             0 0
#+end_src

* Алгоритм
Определяем тип прошивки. Если это RTOS/Bare-Metal, выполняем все предварительные шаги и загружаем прошивку в дизасм:
- идентифицируем периферию с помощью SVD (или других доступных источников);
- определяем основные примитивы: задачи, очереди, примитивы синхронизации, управление памятью, таймеры;
- идем от обратного: находим доступы к периферии, определяем соответствующие функции чтения/записи/настройки. Изолируем эту логику, чтобы исследовать только интересующие нас части прошивки.
Иначе: анализируем файловую систему, ищем приложения, реализующие бизнес-логику:
