#+title: M1 File

* Компиляция
#+begin_src c
#include <stdio.h>
int main()
{
        printf("Hello world!");
        return 0;
}
#+end_src

#+begin_src shell
$> gcc helloworld.c -o helloworld -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-9QDOt0/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)
COLLECT_GCC_OPTIONS='-o' 'helloworld' '-v' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86

...
#+end_src

#+begin_src shell
/usr/lib/gcc/x86_64-linux-gnu/9/cc1 -quiet -v -imultiarch x86_64-linux-gnu helloworld.c -quiet -dumpbase helloworld.c -mtune=generic -march=x86-64 -auxbase helloworld -version -fasynchronous-unwind-tables -fstack-protector-strong -Wformat -Wformat-security -fstack-clash-protection -fcf-protection -o /tmp/ccMGy2uf.s
#+end_src

Препроцессинг #include, #define, обработка if/ifdef
Разбор синтаксиса
Семантический анализ
генерация осемблерного листнинга .s

1. Препроцессор
2. Компиляция в asm
3. Компиляция в машинный код
4. Компановка

* Загрузка в память
** PE header :header:pe:
*** COFF File Header
| Machine              | Указывает архитектуру исполняемого файла (AMD64, ARM64, MIPS и т. д.)                                                                                                             |
| NumberOfSections     | Указывает количество секций в исполняемом файле.                                                                                                                                  |
| TimeDateStamp        | Время создания файла (начиная с 1 января 1970 00:00).                                                                                                                             |
| PointerToSymbolTable | Указатель на символьную таблицу COFF. Устаревшее поле, так как отладочная информация COFF больше не используется, а само поле инициализировано нулями.                            |
| SizeOfOptionalHeader | Количество записей в символьной таблице COFF. Использовалось для поиска таблицы строк, что располагалась после символьной таблицы. Устаревшее поле.                               |
| Characteristics      | Характеристики, указывающие на атрибуты файла (например, что программа поддерживает адреса больше 2 гигабайт, что исполняемый файл системный или что он динамическая библиотека). |

*** Optional Header
| Magic                       | Целочисленное указывает, является ли файл PE32 (0x10B) или PE32+ (0x20B). Их разница в том, что последний может поддерживать 64-битные адреса. Есть также ROM-файлы (0x107).                                                                                                                                                                |
| MajorLinkerVersion          | Номер основной версии линковщика.                                                                                                                                                                                                                                                                                                           |
| MinorLinkerVersion          | Младший номер версии линковщика.                                                                                                                                                                                                                                                                                                            |
| SizeOfCode                  | Размер кодовой секции (.text) или же сумма всех секций с кодом.                                                                                                                                                                                                                                                                             |
| SizeOfInitializedData       | Размер инициализированной секции данных (.data) или же сумма всех секций с инициализированными данными.                                                                                                                                                                                                                                     |
| SizeOfUninitializedData     | Размер неинициализированной секции данных (.bss) или же сумма всех секций с неинициализированными данными.                                                                                                                                                                                                                                  |
| AddressOfEntryPoint         | Адрес точки входа относительно базового адреса исполняемого файла при загрузке его в память.                                                                                                                                                                                                                                                |
| BaseOfCode                  | Адрес кодовой секции относительно базового адреса исполняемого файла при загрузке его в память.                                                                                                                                                                                                                                             |
| BaseOfData (только PE32)    | Базовый адрес исполняемого файла. Должен быть кратен 64 килобайтам.                                                                                                                                                                                                                                                                         |
| SectionAlignment            | Значение в байтах, по которому будут выравниваться секции, когда они будут загружаться в память. Поле должно быть больше или равно полю FileAlignment. Стандартное значение - размер страницы памяти в текущей архитектуре (4096 байт для AMD64).                                                                                           |
| FileAlignment               | Значение в байтах, по которому выравниваются "сырые" данные секций в исполняемом файле. Значение должно быть степенью 2 в диапазоне чисел от 512 до 64 килобайт. Если SectionAlignment меньше размера страницы памяти в текущей архитектуре, FileAlignment обязан соответствовать SectionAlignment. По стандарту это поле равно 512 байтам. |
| MajorOperatingSystemVersion | Номер основной версии ОС, под которую собран исполняемый файл.                                                                                                                                                                                                                                                                              |
| MinorOperatingSystemVersion | Номер минимальной версии ОС, для которой будет работать исполняемый файл.                                                                                                                                                                                                                                                                   |
| MajorImageVersion           | Основной номер версии исполняемого файла.                                                                                                                                                                                                                                                                                                   |
| MinorImageVersion           | Младший номер версии исполняемого файла.                                                                                                                                                                                                                                                                                                    |
| MajorSubsystemVersion       | Основной номер подсистемы.                                                                                                                                                                                                                                                                                                                  |
| MinorSubsystemVersion       | Младший номер подсистемы.                                                                                                                                                                                                                                                                                                                   |
| Win32VersionValue           | Зарезервированное поле, обязано быть 0.                                                                                                                                                                                                                                                                                                     |
| SizeOfImage                 | Размер исполняемого файла в байтах, включая все заголовки. Это поле должно быть кратно полю SectionAlignment.                                                                                                                                                                                                                               |
| SizeOfHeaders               | Сумма всех заголовков исполняемого файла. Округляется до значения, кратного FileAlignment.                                                                                                                                                                                                                                                  |
| CheckSum                    | Поле с чек-суммой исполняемого файла. Преимущественно используется во время загрузки системы для драйверов и DLL, а также для DLL, что используются в важных процессах Windows.                                                                                                                                                             |
| Subsystem                   | Номер подсистемы. Например, драйверы в этом поле будут иметь 1, а графические приложения 2.                                                                                                                                                                                                                                                 |
| DllCharacteristics          | Характеристики DLL. Например, если DLL поддерживает NX, то здесь будет 0x100.                                                                                                                                                                                                                                                               |
| SizeOfStackReserve          | Размер стека для резервирования, фиксируется только полем SizeOfStackCommit.                                                                                                                                                                                                                                                                |
| SizeOfStackCommit           | Размер стека для его фиксации.                                                                                                                                                                                                                                                                                                              |
| SizeOfHeapReserve           | Размер кучи для резервирования, фиксируется только полем SizeOfHeapCommit.                                                                                                                                                                                                                                                                  |
| SizeOfHeapCommit            | Размер кучи для её фиксации.                                                                                                                                                                                                                                                                                                                |
| LoaderFlags                 | Зарезервированное поле, обязано быть 0.                                                                                                                                                                                                                                                                                                     |
| NumberOfRvaAndSizes         | Количество записей в заголовке данных (о нём ниже) в оставшемся свободном пространстве опционального заголовка. Каждая запись описывает смещение и размер записи.                                                                                                                                                                           |
*** Directory Header
Смещение до таблиц относительно базового адреса и размер таблиц
#+begin_src c
typedef struct _IMAGE_DATA_DIRECTORY {
    uint32_t   VirtualAddress;
    uint32_t   Size;
} IMAGE_DATA_DIRECTORY, *PIMAGE_DATA_DIRECTORY;
#+end_src
По стандарту, все таблицы расположены в следующем порядке:

Таблица экспортов (секция .edata).
Таблица импортов (секция .idata).
Таблица ресурсов (секция .rsrc).
Таблица исключений (секция .pdata).
Таблица сертификата с электронной подписью файла.
Таблица релокаций (секция .reloc).
Отладочная таблица (секция .debug).
Архитектурная таблица (зарезервирована, обязана быть 0).
GlobalPtr таблица - RVA значения, которое должно быть сохранено GP-регистром (Global Pointer Register).
TLS таблица (Thread Local Storage, секция .tls).
Таблица конфигурации загрузчика.
Bound Import таблица.
IAT (Import Address Table), не стоит путать с таблицей импортов.
Таблица отложенных импортов.
*** Section Header
| Название поля        | Описание поля                                                                                                 |
| Name                 | Имя секции (до 8 байт).                                                                                       |
| VirtualSize          | Размер секции в памяти.                                                                                       |
| VirtualAddress       | Виртуальный адрес секции относительно базового адреса исполняемого файла.                                     |
| SizeOfRawData        | Размер инициализированных данных на диске.                                                                    |
| PointerToRawData     | Указатель на первую страницу секции.                                                                          |
| PointerToRelocations | Указатель на начало записей в таблице релокаций. Для исполняемых файлов устанавливается 0.                    |
| PointerToLinenumbers | Указатель на начало записей в отладочной таблице COFF. Всегда 0, так как отладочная информация COFF устарела. |
| NumberOfRelocations  | Количество записей в таблице релокаций. Инициализировано нулём для исполняемых файлов.                        |
| NumberOfLinenumbers  | Количество записей в отладочной таблице COFF. Всегда 0, так как отладочная информация COFF устарела.          |
| Characteristics      | Флаги характеристик секции.                                                                                   |

** ELF header :header:elf:
*** e_ident
| EI_MAG0 - EI_MAG3   | Сигнатура файла (0x7F454C46).                                            |
| EI_CLASS            | Класс файла (x86 или x64).                                               |
| EI_DATA             | Последовательность байтов (Big Endian или Little Endian).                |
| EI_VERSION          | Версия заголовка ELF.                                                    |
| EI_OSABI            | Специфичные расширения для ОС или ABI, используемые в исполняемом файле. |
| EI_ABIVERSION       | Версия ABI.                                                              |
| EI_PAD - EI_PAD + 6 | Зарезервированные байты массива e_ident для будущих обновлений формата.  |
*** e_
| e_type      | Тип файла (исполняемый файл, динамическая библиотека и т.п.).                                               |
| e_machine   | Аппаратная архитектура, под которую был собран исполняемый файл (x64, MIPS, ARM64 и т. д.).                 |
| e_version   | Номер версии формата.                                                                                       |
| e_entry     | Виртуальный адрес точки входа в программу.                                                                  |
| e_phoff     | Смещение до таблицы заголовков программы.                                                                   |
| e_shoff     | Смещение до таблицы секций программы.                                                                       |
| e_flags     | Зависящие от процессора специфичные флаги для исполняемого файла.                                           |
| e_ehsize    | Размер заголовка исполняемого файла в байтах (x86 - 52, x64 - 64).                                          |
| e_phentsize | Размер одного заголовка в байтах (x86 - 32, x64 - 56). Все заголовки имеют одинаковый размер                |
| e_phnum     | Количество заголовков в исполняемом файле.                                                                  |
| e_shentsize | Размер одного заголовка секции в байтах (x86 - 40, x64 - 64). Все заголовки секций имеют одинаковый размер. |
| e_shnum     | Число заголовков секций.                                                                                    |
| e_shstrndx  | Индекс записи в таблице заголовков секций, что описывает таблицу названий секций                            |

*** p_
| p_type              | Тип сегмента, описываемый заголовком, и как необходимо интерпретировать его поля. |
| p_flags (для ELF64) | Флаги сегмента (разрешения на чтение, запись и исполнение).                       |
| p_offset            | Смещение от начала файла до самого сегмента.                                      |
| p_vaddr             | Виртуальный адрес сегмента в памяти, куда он должен быть загружен.                |
| p_paddr             | Физический адрес сегмента.                                                        |
| p_filesz            | Размер сегмента в файле (на диске).                                               |
| p_memsz             | Размер сегмента в памяти.                                                         |
| p_flags (для ELF32) | Флаги сегмента (разрешения на чтение, запись и исполнение).                       |
| p_align             | Выравнивание сегмента.                                                            |

*** sh_
| sh_name      | Смещение строки, содержащей название секции, относительно начала таблицы названий секций.          |
| sh_type      | Описывает тип секции (например, секция содержит таблицу символов).                                 |
| sh_flags     | Атрибуты секции (например, секция содержит исполняемые инструкции).                                |
| sh_addr      | Адрес, куда секция должна быть загружена (если вообще должна быть загружена, иначе здесь будет 0). |
| sh_offset    | Смещение секции от начала исполняемого файла.                                                      |
| sh_size      | Размер секции в файле.                                                                             |
| sh_link      | Индекс ассоциированной секции (зависит от sh_type и sh_info).                                      |
| sh_info      | Дополнительная информация о секции.                                                                |
| sh_addralign | Выравнивание секции.                                                                               |
| sh_entsize   | Размер каждой записи в байтах (только в том случае, если массив записей фиксированного размера).   |

** Sections :sections:elf:pe:
*** common
| .text | Кодовая секция. Здесь содержится весь код программы.                                                          |
| .data | Секция инициализированных данных. Здесь находятся различные глобальные переменные, таблицы и т.п.             |
| .bss  | Секция неинициализированных данных. Здесь находятся различные неинициализированные переменные, массивы и т.п. |

*** PE sections
| .edata | Секция таблицы экспорта. Содержит в себе информацию о функциях, которые могут использовать другие исполняемые файлы. Преимущественно встерчается у DLL и драйверов. |
| .idata | Секция таблицы импортов. Содержит информацию о импортируемых функциях исполняемого файла.                                                                           |
| .rsrc  | Секция таблицы ресурсов. В ней содержатся ресурсы приложения (например, изображения или шрифты).                                                                    |
| .pdata | Секция таблицы исключений. Здесь содержатся все функции, используемые для обработки исключений.                                                                     |
| .reloc | Секция таблицы релокаций. Секция содержит в себе всю информацию для всех релокаций относительно базового адреса исполняемого файла.                                 |
| .debug | Секция отладочных символов. Содержит всю необходимую отладочную информацию, сгенерированную компилятором.                                                           |
| .tls   | Секция локального хранилища потоков. Содержит в себе все объекты, которые являются локальными для каждого отдельного потока, что запускают какой-либо код.          |

*** ElF sections
| .rodata                 | Секция данных только для чтения. Обычно здесь лежат строки.             |
| .shstrtab, .strtab      | Таблица названий секций.                                                |
| .stab, .stabstr         | Секция отладочных символов.                                             |
| .rel<name>, .rela<name> | Секция релокаций конкретной секции, например .rel.text или .rela.text.  |
| .init                   | Секция содержит инструкции для инициализации программы.                 |
| .line                   | Секция, что содержит в себе информацию о номерах строк для отладки.     |
| .fini                   | Содержит инструкции, что должны исполниться после выполнения программы. |
| .comment, .note         | Содержат комментарии и различные заметки.                               |
| .dynsym                 | Содержит в себе информацию описываемых импортируемых функциях.          |
| .dynstr                 | Содержит в себе названия импортируемых функций.                         |
| .got                    | Содержит глобальную таблицу смещений                                    |


** Процесс загрузки исполняемого файла

1. Прочитать заголовки исполняемого файла.
2. Сохранить информацию о размере, секциях, базовом адресе, таблицах исполняемого файла.
3. Выделить адрес и количество страниц памяти, удовлетворяющие требованиям исполняемого файла.
4. Перенести секции исполняемого файла в выделенный участок памяти.
5. Обработать необходимые таблицы, например, таблицу импортов и релокаций.
6. Создать процесс и запустить исполняемый файл.

* Алгоритмы анализа :static:algorithm:
** Алгоритм анализа файла
:PROPERTIES:
:ID:       87f103ba-dd17-42e4-9a47-76ddb6afa8ae
:END:
1. Формат
2. Строки
3. Тип исполняемого файла


   1. file, magika, DiE
   2. strings -t [offset] d,o,x [dec, oct, hex]
   3. DiE - comiler, language, tool

** Статический анализ :static:tools:
| Класс инструментов                  | Основная задача                                             | Что помогает посмотреть                                                        | Что позволяет получить                                                   | Примеры инструментов                                                |
| Обозреватели файлов                 | Разбор контейнера файла                                     | Заголовки, секции, импорты, экспорты, релокации                                | Детали о мета-данных файла                                               | PE-bear, CFF Explorer, readelf, objdump, otool, любые hex-редакторы |
| Дизассемблеры                       | Представление машинного кода в ассемблере                   | Инструкции, функции, переходы, кросс-вызовы                                    | Ассемблерный листинг                                                     | IDA, Ghidra, Binary Ninja, radare2                                  |
| Декомпиляторы                       | Восстановление логики на псевдокоде                         | Управление потоком, переменные, вызовы                                         | Псевдокод на ЯП высокого уровня                                          | IDA Hex-Rays, Ghidra Decompiler, Binary Ninja                       |
| Статические сигнатурные анализаторы | Поиск известных шаблонов                                    | Сигнатуры, импорты библиотек, паттерны кода, правила, эвристики                | Идентификация некоторых компонентов, массовая классификация и фильтрация | YARA, Detect It Easy, capa, strings+grep                            |
| Hex-редакторы                       | Посмотреть на файлы "как они есть" в 16-ричной форме записи | Оригинальные данные, которые хранятся в памяти, на флешке, на жёстком диске... | Информацию о том, какие данные хранятся на самом деле                    | ImHex, 010 editor, HxD, hiew                                        |

** Алгоритм статического анализа
- [[87f103ba-dd17-42e4-9a47-76ddb6afa8ae][Формат файла]]
- Заголовки и секции
- Строки и ресурсы
- Импорты и экспорты
- Дизасм/декомпил
  - ключевые функции
  - комментарии
  - концепт

** Алгоритм анализа по строкам
- Найти строки
- Гуглить найденные строки
- ???

** Анализ по системным и библиотечным вызовам :reverse:libs:
**** Советы свыше
Во время анализа произвольного исполняемого файла при помощи Ghidra вы видите следующую картину в окне Functions либо Symbols:

Необходимо выяснить, что за интерфейс у функции SDL_PollEvent и добавить его в список типов у проекта.

Шаг 1.
Буквально гуглим, что за функции перед нами:

Шаг 2.
Видим, что это библиотека SDL2. Гуглим более таргетно нашу функцию, и открываем документацию:

Шаг 3.
Сигнатуру мы нашли, но единственный аргумент имеет ещё один кастомный тип данных. Ищем в той же документации эту структуру:


Шаг 4.
Добавить эту структуру данных руками будет затруднительно, поэтому берём файл с описанием этой структуры с GitHub и импортируем его в интерфейсе Ghidra:

File > Parse C Source > Add files to parse.


Примечание: Чтобы не получать ошибки вида "Error: Undefined data type "Uint32" загрузите ещё файл SDL_stdinc.h. Либо скачайте весь проект и добавьте include в path проекта.

В итоге мы получим в окне Data Types нужный нам тип:


Во время анализа произвольного исполняемого файла при помощи Ghidra вы видите следующую картину в окне Functions либо Symbols:

Необходимо выяснить, что за интерфейс у функции SDL_PollEvent и добавить его в список типов у проекта.

Шаг 1.
Буквально гуглим, что за функции перед нами:


Шаг 2.
Видим, что это библиотека SDL2. Гуглим более таргетно нашу функцию, и открываем документацию:


Шаг 3.
Сигнатуру мы нашли, но единственный аргумент имеет ещё один кастомный тип данных. Ищем в той же документации эту структуру:


Шаг 4.
Добавить эту структуру данных руками будет затруднительно, поэтому берём файл с описанием этой структуры с GitHub и импортируем его в интерфейсе Ghidra:

File > Parse C Source > Add files to parse.


Примечание: Чтобы не получать ошибки вида "Error: Undefined data type "Uint32" загрузите ещё файл SDL_stdinc.h. Либо скачайте весь проект и добавьте include в path проекта.

В итоге мы получим в окне Data Types нужный нам тип:

Описание результата
Теперь мы можем поправить сигнатуру функции SDL_PollEvent, что упростит дальнейший анализ кода.

Описание результата
Теперь мы можем поправить сигнатуру функции SDL_PollEvent, что упростит дальнейший анализ кода.


**** Заметки

Алгоритм:
- ELF
- MachO
- PE


#+begin_src C
#include "stdio.h"

int main(int argc, char** argv)
{
        printf("Hello world");
        return 0;
}
#+end_src

#+RESULTS:
: Hello world


*** ELF
**** READELF :readelf:
***** readelf_headers
Читаем ELF Header и смотрим PT_INTERP где будет указан dynamic loader
readelf -l *target*

#+begin_src shell :dir . :results output
/opt/homebrew/opt/binutils/bin/greadelf -l Practice/hello_worlds/hello_world_ELF_ARM
#+end_src

#+RESULTS:
#+begin_example

Elf file type is DYN (Position-Independent Executable file)
Entry point 0x680
There are 10 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x0000000000000230 0x0000000000000230  R      0x8
  INTERP         0x0000000000000294 0x0000000000000294 0x0000000000000294
                 0x000000000000001b 0x000000000000001b  R      0x1
      [Requesting program interpreter: /lib/ld-linux-aarch64.so.1]
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000000009a8 0x00000000000009a8  R E    0x10000
  LOAD           0x000000000000fdc8 0x000000000001fdc8 0x000000000001fdc8
                 0x0000000000000270 0x0000000000000278  RW     0x10000
  DYNAMIC        0x000000000000fdd8 0x000000000001fdd8 0x000000000001fdd8
                 0x00000000000001e0 0x00000000000001e0  RW     0x8
  NOTE           0x0000000000000270 0x0000000000000270 0x0000000000000270
                 0x0000000000000024 0x0000000000000024  R      0x4
  NOTE           0x0000000000000918 0x0000000000000918 0x0000000000000918
                 0x0000000000000090 0x0000000000000090  R      0x4
  GNU_EH_FRAME   0x000000000000080c 0x000000000000080c 0x000000000000080c
                 0x000000000000003c 0x000000000000003c  R      0x4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x000000000000fdc8 0x000000000001fdc8 0x000000000001fdc8
                 0x0000000000000238 0x0000000000000238  R      0x1

 Section to Segment mapping:
  Segment Sections...
   00
   01     .interp
   02     .note.gnu.build-id .interp .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .init .plt .text .fini .rodata .eh_frame_hdr .eh_frame .note.ABI-tag .note.package
   03     .init_array .fini_array .dynamic .got .got.plt .data .bss
   04     .dynamic
   05     .note.gnu.build-id
   06     .note.ABI-tag .note.package
   07     .eh_frame_hdr
   08
   09     .init_array .fini_array .dynamic .got
#+end_example

Общая схема
В память грузится libc и становится первым userspace кодом
 kernel
  - maps exec
  - maps ld-linux
  - jumps to ld-linux
  (kernel читает header, маппит экзек и ld в память, передает управление ld)
  dynamic linker
  - read DT_NEEDED
  - load .so
  - resolve

***** readelf_imports
#+begin_src shell :dir . :results output
/opt/homebrew/opt/binutils/bin/greadelf -Ws Practice/hello_worlds/hello_world_ELF_ARM
#+end_src

#+RESULTS:
#+begin_example

Symbol table '.dynsym' contains 10 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 00000000000005d0     0 SECTION LOCAL  DEFAULT   10 .init
     2: 0000000000020028     0 SECTION LOCAL  DEFAULT   24 .data
     3: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __libc_start_main@GLIBC_2.34 (2)
     4: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterTMCloneTable
     5: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND __cxa_finalize@GLIBC_2.17 (3)
     6: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
     7: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND abort@GLIBC_2.17 (3)
     8: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_registerTMCloneTable
     9: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND printf@GLIBC_2.17 (3)

Symbol table '.symtab' contains 91 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000270     0 SECTION LOCAL  DEFAULT    1 .note.gnu.build-id
     2: 0000000000000294     0 SECTION LOCAL  DEFAULT    2 .interp
     3: 00000000000002b0     0 SECTION LOCAL  DEFAULT    3 .gnu.hash
     4: 00000000000002d0     0 SECTION LOCAL  DEFAULT    4 .dynsym
     5: 00000000000003c0     0 SECTION LOCAL  DEFAULT    5 .dynstr
     6: 0000000000000454     0 SECTION LOCAL  DEFAULT    6 .gnu.version
     7: 0000000000000468     0 SECTION LOCAL  DEFAULT    7 .gnu.version_r
     8: 0000000000000498     0 SECTION LOCAL  DEFAULT    8 .rela.dyn
     9: 0000000000000558     0 SECTION LOCAL  DEFAULT    9 .rela.plt
    10: 00000000000005d0     0 SECTION LOCAL  DEFAULT   10 .init
    11: 00000000000005f0     0 SECTION LOCAL  DEFAULT   11 .plt
    12: 0000000000000680     0 SECTION LOCAL  DEFAULT   12 .text
    13: 00000000000007e4     0 SECTION LOCAL  DEFAULT   13 .fini
    14: 00000000000007fc     0 SECTION LOCAL  DEFAULT   14 .rodata
    15: 000000000000080c     0 SECTION LOCAL  DEFAULT   15 .eh_frame_hdr
    16: 0000000000000848     0 SECTION LOCAL  DEFAULT   16 .eh_frame
    17: 0000000000000918     0 SECTION LOCAL  DEFAULT   17 .note.ABI-tag
    18: 0000000000000938     0 SECTION LOCAL  DEFAULT   18 .note.package
    19: 000000000001fdc8     0 SECTION LOCAL  DEFAULT   19 .init_array
    20: 000000000001fdd0     0 SECTION LOCAL  DEFAULT   20 .fini_array
    21: 000000000001fdd8     0 SECTION LOCAL  DEFAULT   21 .dynamic
    22: 000000000001ffb8     0 SECTION LOCAL  DEFAULT   22 .got
    23: 000000000001ffe8     0 SECTION LOCAL  DEFAULT   23 .got.plt
    24: 0000000000020028     0 SECTION LOCAL  DEFAULT   24 .data
    25: 0000000000020038     0 SECTION LOCAL  DEFAULT   25 .bss
    26: 0000000000000000     0 SECTION LOCAL  DEFAULT   26 .comment
    27: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS Scrt1.o
    28: 0000000000000680     0 NOTYPE  LOCAL  DEFAULT   12 $x
    29: 000000000000085c     0 NOTYPE  LOCAL  DEFAULT   16 $d
    30: 0000000000000918     0 NOTYPE  LOCAL  DEFAULT   17 $d
    31: 0000000000000918    32 OBJECT  LOCAL  DEFAULT   17 __abi_tag
    32: 00000000000007fc     0 NOTYPE  LOCAL  DEFAULT   14 $d
    33: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS crti.o
    34: 00000000000006b4     0 NOTYPE  LOCAL  DEFAULT   12 $x
    35: 00000000000006b4    20 FUNC    LOCAL  DEFAULT   12 call_weak_fn
    36: 00000000000005d0     0 NOTYPE  LOCAL  DEFAULT   10 $x
    37: 00000000000007e4     0 NOTYPE  LOCAL  DEFAULT   13 $x
    38: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS crtn.o
    39: 00000000000005e0     0 NOTYPE  LOCAL  DEFAULT   10 $x
    40: 00000000000007f0     0 NOTYPE  LOCAL  DEFAULT   13 $x
    41: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS crtstuff.c
    42: 00000000000006e0     0 NOTYPE  LOCAL  DEFAULT   12 $x
    43: 00000000000006e0     0 FUNC    LOCAL  DEFAULT   12 deregister_tm_clones
    44: 0000000000000710     0 FUNC    LOCAL  DEFAULT   12 register_tm_clones
    45: 0000000000020030     0 NOTYPE  LOCAL  DEFAULT   24 $d
    46: 000000000000074c     0 FUNC    LOCAL  DEFAULT   12 __do_global_dtors_aux
    47: 0000000000020038     1 OBJECT  LOCAL  DEFAULT   25 completed.0
    48: 000000000001fdd0     0 NOTYPE  LOCAL  DEFAULT   20 $d
    49: 000000000001fdd0     0 OBJECT  LOCAL  DEFAULT   20 __do_global_dtors_aux_fini_array_entry
    50: 00000000000007a0     0 FUNC    LOCAL  DEFAULT   12 frame_dummy
    51: 000000000001fdc8     0 NOTYPE  LOCAL  DEFAULT   19 $d
    52: 000000000001fdc8     0 OBJECT  LOCAL  DEFAULT   19 __frame_dummy_init_array_entry
    53: 0000000000000870     0 NOTYPE  LOCAL  DEFAULT   16 $d
    54: 0000000000020038     0 NOTYPE  LOCAL  DEFAULT   25 $d
    55: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS hello_world.c
    56: 00000000000007a8     0 NOTYPE  LOCAL  DEFAULT   12 $x
    57: 0000000000000800     0 NOTYPE  LOCAL  DEFAULT   14 $d
    58: 000000000000004b     0 NOTYPE  LOCAL  DEFAULT   26 $d
    59: 00000000000008d8     0 NOTYPE  LOCAL  DEFAULT   16 $d
    60: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS crtstuff.c
    61: 0000000000000914     0 NOTYPE  LOCAL  DEFAULT   16 $d
    62: 0000000000000914     0 OBJECT  LOCAL  DEFAULT   16 __FRAME_END__
    63: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS
    64: 000000000001fdd8     0 OBJECT  LOCAL  DEFAULT  ABS _DYNAMIC
    65: 000000000000080c     0 NOTYPE  LOCAL  DEFAULT   15 __GNU_EH_FRAME_HDR
    66: 000000000001ffb8     0 OBJECT  LOCAL  DEFAULT  ABS _GLOBAL_OFFSET_TABLE_
    67: 00000000000005f0     0 NOTYPE  LOCAL  DEFAULT   11 $x
    68: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __libc_start_main@GLIBC_2.34
    69: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_deregisterTMCloneTable
    70: 0000000000020028     0 NOTYPE  WEAK   DEFAULT   24 data_start
    71: 0000000000020038     0 NOTYPE  GLOBAL DEFAULT   25 __bss_start__
    72: 0000000000000000     0 FUNC    WEAK   DEFAULT  UND __cxa_finalize@GLIBC_2.17
    73: 0000000000020040     0 NOTYPE  GLOBAL DEFAULT   25 _bss_end__
    74: 0000000000020038     0 NOTYPE  GLOBAL DEFAULT   24 _edata
    75: 00000000000007e4     0 FUNC    GLOBAL HIDDEN    13 _fini
    76: 0000000000020040     0 NOTYPE  GLOBAL DEFAULT   25 __bss_end__
    77: 0000000000020028     0 NOTYPE  GLOBAL DEFAULT   24 __data_start
    78: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND __gmon_start__
    79: 0000000000020030     0 OBJECT  GLOBAL HIDDEN    24 __dso_handle
    80: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND abort@GLIBC_2.17
    81: 00000000000007fc     4 OBJECT  GLOBAL DEFAULT   14 _IO_stdin_used
    82: 0000000000020040     0 NOTYPE  GLOBAL DEFAULT   25 _end
    83: 0000000000000680    52 FUNC    GLOBAL DEFAULT   12 _start
    84: 0000000000020040     0 NOTYPE  GLOBAL DEFAULT   25 __end__
    85: 0000000000020038     0 NOTYPE  GLOBAL DEFAULT   25 __bss_start
    86: 00000000000007a8    60 FUNC    GLOBAL DEFAULT   12 main
    87: 0000000000020038     0 OBJECT  GLOBAL HIDDEN    24 __TMC_END__
    88: 0000000000000000     0 NOTYPE  WEAK   DEFAULT  UND _ITM_registerTMCloneTable
    89: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND printf@GLIBC_2.17
    90: 00000000000005d0     0 FUNC    GLOBAL HIDDEN    10 _init
#+end_example


**** OBJDUMP :objdump:
***** objdump_headers
#+begin_src shell :dir . :results output
/opt/homebrew/opt/binutils/bin/gobjdump -f  Practice/hello_worlds/hello_world_ELF_x86
#+end_src

#+RESULTS:
:
: Practice/hello_worlds/hello_world_ELF_x86:     file format elf64-x86-64
: architecture: i386:x86-64, flags 0x00000150:
: HAS_SYMS, DYNAMIC, D_PAGED
: start address 0x0000000000001060
:

#+begin_src shell :dir . :results output
/opt/homebrew/opt/binutils/bin/gobjdump -h  Practice/hello_worlds/hello_world_ELF_x86
#+end_src

#+RESULTS:
#+begin_example

Practice/hello_worlds/hello_world_ELF_x86:     file format elf64-x86-64

Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .note.gnu.property 00000030  0000000000000350  0000000000000350  00000350  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  1 .note.gnu.build-id 00000024  0000000000000380  0000000000000380  00000380  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .interp       0000001c  00000000000003a4  00000000000003a4  000003a4  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .gnu.hash     00000024  00000000000003c0  00000000000003c0  000003c0  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .dynsym       000000a8  00000000000003e8  00000000000003e8  000003e8  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  5 .dynstr       0000008f  0000000000000490  0000000000000490  00000490  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 .gnu.version  0000000e  0000000000000520  0000000000000520  00000520  2**1
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  7 .gnu.version_r 00000030  0000000000000530  0000000000000530  00000530  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  8 .rela.dyn     000000c0  0000000000000560  0000000000000560  00000560  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  9 .rela.plt     00000018  0000000000000620  0000000000000620  00000620  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 10 .init         0000001b  0000000000001000  0000000000001000  00001000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 11 .plt          00000020  0000000000001020  0000000000001020  00001020  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 12 .plt.got      00000010  0000000000001040  0000000000001040  00001040  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 13 .plt.sec      00000010  0000000000001050  0000000000001050  00001050  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 14 .text         00000117  0000000000001060  0000000000001060  00001060  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 15 .fini         0000000d  0000000000001178  0000000000001178  00001178  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 16 .rodata       00000010  0000000000002000  0000000000002000  00002000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 17 .eh_frame_hdr 00000034  0000000000002010  0000000000002010  00002010  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 18 .eh_frame     000000ac  0000000000002048  0000000000002048  00002048  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 19 .note.ABI-tag 00000020  00000000000020f4  00000000000020f4  000020f4  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 20 .note.package 00000078  0000000000002114  0000000000002114  00002114  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 21 .init_array   00000008  0000000000003db8  0000000000003db8  00002db8  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 22 .fini_array   00000008  0000000000003dc0  0000000000003dc0  00002dc0  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 23 .dynamic      000001f0  0000000000003dc8  0000000000003dc8  00002dc8  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 24 .got          00000048  0000000000003fb8  0000000000003fb8  00002fb8  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 25 .data         00000010  0000000000004000  0000000000004000  00003000  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 26 .bss          00000008  0000000000004010  0000000000004010  00003010  2**0
                  ALLOC
 27 .comment      00000025  0000000000000000  0000000000000000  00003010  2**0
                  CONTENTS, READONLY
#+end_example

***** objdump_imports
- GCC

#+begin_src shell :dir . :results output
/opt/homebrew/opt/binutils/bin/gobjdump -T  Practice/hello_worlds/hello_world_ELF_x86
#+end_src

#+RESULTS:
#+begin_example

Practice/hello_worlds/hello_world_ELF_x86:     file format elf64-x86-64

DYNAMIC SYMBOL TABLE:
0000000000000000      DF *UND*	0000000000000000 (GLIBC_2.34) __libc_start_main
0000000000000000  w   D  *UND*	0000000000000000  Base        _ITM_deregisterTMCloneTable
0000000000000000      DF *UND*	0000000000000000 (GLIBC_2.2.5) printf
0000000000000000  w   D  *UND*	0000000000000000  Base        __gmon_start__
0000000000000000  w   D  *UND*	0000000000000000  Base        _ITM_registerTMCloneTable
0000000000000000  w   DF *UND*	0000000000000000 (GLIBC_2.2.5) __cxa_finalize
#+end_example


- LLVM

#+begin_src shell :dir . :results output
/opt/homebrew/opt/llvm/bin/llvm-objdump -T  Practice/hello_worlds/hello_world_ELF_x86
#+end_src

#+RESULTS:
#+begin_example

Practice/hello_worlds/hello_world_ELF_x86:	file format elf64-x86-64

DYNAMIC SYMBOL TABLE:
0000000000000000      DF *UND*	0000000000000000 (GLIBC_2.34) __libc_start_main
0000000000000000  w   D  *UND*	0000000000000000              _ITM_deregisterTMCloneTable
0000000000000000      DF *UND*	0000000000000000 (GLIBC_2.2.5) printf
0000000000000000  w   D  *UND*	0000000000000000              __gmon_start__
0000000000000000  w   D  *UND*	0000000000000000              _ITM_registerTMCloneTable
0000000000000000  w   DF *UND*	0000000000000000 (GLIBC_2.2.5) __cxa_finalize
#+end_example


*** Macho
Общая схема
kernel
читает header, маппит экзек ищет LC_LOAD_DYLINKER (~ PT_INTERP) маппит dyld (~ ld)
DT_NEEDED ~ LC_LOAD_DYLIB


#+begin_src bash
ascher@ Practice % otool -L hello_world
hello_world:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1356.0.0)
#+end_src

#+begin_src bash
ascher@ Practice % dyld_info hello_world
hello_world [arm64]:
    -platform:
        platform     minOS      sdk
           macOS     26.0      26.2
    -uuid:
        9A3E6970-CB5C-36BB-BC4B-1F78A7FB615F
    -segments:
        load-offset   segment  section       sect-size  seg-size   init/max-prot
        0x00000000    __TEXT                                16KB    r.x/r.x
        0x100000460             __text               60
        0x10000049C             __stubs              12
        0x1000004A8             __cstring            12
        0x1000004B4             __unwind_info        88
        0x00004000    __DATA_CONST                          16KB    rw./rw.
        0x100004000             __got                 8
    -linked_dylibs:
        attributes     load path
                       /usr/lib/libSystem.B.dylib
#+end_src

#+begin_src bash
ascher@ Practice % objdump -T hello_world

hello_world:     file format mach-o-arm64

DYNAMIC SYMBOL TABLE:
0000000100000000 g       0f SECT   01 0010 [.text] __mh_execute_header
0000000100000460 g       0f SECT   01 0000 [.text] _main
0000000000000000 g       01 UND    00 0100 _printf

#+end_srcДля elf на macos

#+begin_src c
ascher@ Practice % greadelf -d practice_strings | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libcrypto.so.1.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
#+end_src

* Практика
[[id:cd4b5f87-324f-485f-a6e0-250c927351e8][Magic Ball]]
