#+title: M1 Reverse


* Откроем файл :C:
** Некоторые структуры к которым обращается C находятся в юзерспейсе, это и обеспечиваеи платформонезависимость
Платформонезависимо
#+begin_src C
#include <stdio.h>

int main(void) {
  FILE *f = fopen("output", "w");
  if (f == NULL) {
    perror("fopen failed");
    return 1;
  }

  fputs("opened", f);
  fclose(f);
  return 0;
}
#+end_src

POSIX
#+begin_src C
#include <fcntl.h>
#include <unistd.h>

int fd = open("output", O_WRONLY | O_CREAT | O_TRUNC, 0644);
write(fd, "opened", 6);
close(fd);
#+end_src

WinAPI
#+begin_src C
#include <windows.h>

HANDLE h = CreateFileA("output", GENERIC_WRITE, 0, NULL,
                        CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
DWORD written;
WriteFile(h, "opened", 6, &written, NULL);
CloseHandle(h);

#+end_src
** Сеть :C:Sockets:
[[https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D0%BA%D0%B5%D1%82%D1%8B_%D0%91%D0%B5%D1%80%D0%BA%D0%BB%D0%B8][Berkley Sockets - API от BSD]]

*** Пример на Windows
#+begin_src C
#include <winsock2.h>
#include <stdio.h>

#pragma comment(lib, "ws2_32.lib")

int main() {
    WSADATA wsa;
    SOCKET client;
    struct sockaddr_in server;
    char *message = "Hello, server";
    char buffer[4096];
    int bytes_received;

    WSAStartup(MAKEWORD(2, 2), &wsa);

    client = socket(AF_INET, SOCK_STREAM, 0);

    server.sin_family = AF_INET;
    server.sin_port = htons(1337);
    server.sin_addr.s_addr = inet_addr("192.168.0.1");

    connect(client, (struct sockaddr*)&server, sizeof(server));

    send(client, message, strlen(message), 0);

    bytes_received = recv(client, buffer, sizeof(buffer), 0);
    buffer[bytes_received] = '\0';

    printf("Response: %s\n", buffer);

    closesocket(client);
    WSACleanup();

    return 0;
}
#+end_src
*** Паттерн
1. Создание контекста сокета - структуры sockaddr_in
2. Инициализация (часто функции htons()/inet_addr() сериализуют данные в структуру sockaddr_in)
3. connect() - вызывает попытку подключения
4. I/O типа write/read, send/recv, обычно i/o в буфер
5. закрытие соеденения

** Паттерны криптографии :reverse:crypto:openssl:

*** Хэш паттерн

0. XXX – название хеша (например, MD5, или SHA256, или RIPEMD160

1. создание контекста, в котором будут храниться промежуточные результаты вычисления и различные настройки.
#+begin_src C
int XXX_Init(XXX_CTX *c);
#+end_src

2.  добавление данных для вычисления и вычисление промежуточного хэш-значения. Обычно, данные добавляются по частям, вызывается обычно несколько раз
#+begin_src C
int XXX_Update(XXX_CTX *c, const void *data, size_t len);
#+end_src

3. получение итогового результата, первый указатель - буфер который получит значение хэша
#+begin_src C
int XXX_Final(unsigned char *md, XXX_CTX *c);
#+end_src

Опознать, какой алгоритм хеширования используется, почти всегда можно по функции XXX_Init(). В ней заполняется начальное состояние, которое обычно описывается константами. Например:

для SHA1 это [0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476, 0xC3D2E1F0];
для SHA256 это [0x6A09E667, 0xBB67AE85, 0x3C6EF372, 0xA54FF53A, 0x510E527F, 0x9B05688C, 0x1F83D9AB, 0x5BE0CD19]

хеширование через эти три функции в OpenSSL считается устаревшим, и не рекомендуется для использования. Вместо него предпочтительно использовать EVP-функции (от "EnVeloPe" — обертка, оборачивать)

*** [[https://wiki.openssl.org/index.php/EVP][EVP]] :EVP:
 - Паттерн
   1. Вместо отдельных _Init/_Update/_Final для каждого алгоритма теперь надо получить указатель на структуру EVP_MD для нужного алгоритма

#+begin_src C
const EVP_MD *EVP_md2(void);
const EVP_MD *EVP_md4(void);
const EVP_MD *EVP_md5(void);
const EVP_MD *EVP_sha1(void);
const EVP_MD *EVP_sha224(void);
const EVP_MD *EVP_sha256(void);
const EVP_MD *EVP_sha384(void);
const EVP_MD *EVP_sha512(void);
#+end_src

2. затем вызывать EVP-функции, например, как в этом фрагменте:

#+begin_src C
void digest_message (
  const void *msg, size_t msg_len, unsigned char *digest, int *digest_len
) {
  const EVP_MD *md = EVP_sha256();
  EVP_MD_CTX *mdctx;
  if (!digest || !digest_len || *digest_len < EVP_MD_size(md)) handleErrors();
  if((mdctx = EVP_MD_CTX_new()) == NULL) handleErrors();
  if(1 != EVP_DigestInit_ex(mdctx, md, NULL)) handleErrors();
  if(1 != EVP_DigestUpdate(mdctx, msg, msg_len)) handleErrors();
  if(1 != EVP_DigestFinal_ex(mdctx, digest, digest_len)) handleErrors();
  EVP_MD_CTX_free(mdctx);
}

#+end_src
если найти, где заполняются структуры, которые возвращают функции EVP_sha1(), EVP_sha256() и т.п. (имена структур sha1_md, sha256_md и т.п.), то можно заметить, что (после раскрытия цепочки макросов) вызов метода "init" приведет к функции XXX_Init, "update" приведет к XXX_Update, и т.п. То есть, если найти в коде один из методов, реализующий криптографический примитив (не только хеш, но и алгоритм шифрования, подписи, и т.п.), можно найти EVP-структуру, содержащую методы для работы с этим примитивом, и по ней найти все методы.
[[id:28cc51e9-cdf1-4e42-bbc0-bf9abe1a9dfd][Также добавляй примитивы, паттерны как тут]]
Ну и OpenSSL доступен в исходниках же задачка только определить версию


* Алгоритм поиска логики в коде :reverse:ida:
1. Найти участок кода который нужно реверсить - по строкам, по функциям, по пути от начала исполнения, просто то что выглядит так как то что нужно
2. Исследуем то что объявили целью и окрестности
3. Даем имена согласно тому что получилось понять
4. После некоторых успехов/неуспехов стоит расширить фокус и подумать похоже ли то что ты делаешь, на то к чему надо прийти, точно ли ты там где надо
   после п.1-3 может прийти осознание что ты немного не там, но также будет получена новая информация которая пригодится при выполенении алгоритма сначала
5. В конце уже точеченая и как можно более точная работа с восстановлением исходного алгоритма того что оказалось целью

   [[id:139dc0bd-4b0e-462e-a922-d7017ea4e822][Опять виндовый пример]]
